//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.26 at 10:48:45 AM CEST 
//


package org.openforis.collect.mondrian;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * 
 *                 
 *                 Defines a hierarchy.
 *                 You must specify at most one <Relation> or memberReaderClass.
 *                 If you specify none, the hierarchy is assumed to come from the same
 *                 fact table of the current cube.
 *                 
 *             
 * 
 * <p>Java class for Hierarchy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Hierarchy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Annotations" type="{}Annotations" minOccurs="0"/>
 *         &lt;group ref="{}Relation" minOccurs="0"/>
 *         &lt;element name="Level" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Annotations" type="{}Annotations" minOccurs="0"/>
 *                   &lt;element name="KeyExpression" type="{}ExpressionView" minOccurs="0"/>
 *                   &lt;element name="NameExpression" type="{}ExpressionView" minOccurs="0"/>
 *                   &lt;element name="CaptionExpression" type="{}ExpressionView" minOccurs="0"/>
 *                   &lt;element name="OrdinalExpression" type="{}ExpressionView" minOccurs="0"/>
 *                   &lt;element name="ParentExpression" type="{}ExpressionView" minOccurs="0"/>
 *                   &lt;element name="Closure" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Table" type="{}Table"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="parentColumn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="childColumn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Property" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="column" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="type" default="String">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="String"/>
 *                                 &lt;enumeration value="Numeric"/>
 *                                 &lt;enumeration value="Integer"/>
 *                                 &lt;enumeration value="Boolean"/>
 *                                 &lt;enumeration value="Date"/>
 *                                 &lt;enumeration value="Time"/>
 *                                 &lt;enumeration value="Timestamp"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="formatter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="caption" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="dependsOnLevelValue" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="approxRowCount" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="table" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="nameColumn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ordinalColumn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="parentColumn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="nullParentValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="type">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="String"/>
 *                       &lt;enumeration value="Numeric"/>
 *                       &lt;enumeration value="Integer"/>
 *                       &lt;enumeration value="Boolean"/>
 *                       &lt;enumeration value="Date"/>
 *                       &lt;enumeration value="Time"/>
 *                       &lt;enumeration value="Timestamp"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="uniqueMembers" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="levelType" default="Regular">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="Regular"/>
 *                       &lt;enumeration value="TimeYears"/>
 *                       &lt;enumeration value="TimeQuarters"/>
 *                       &lt;enumeration value="TimeMonths"/>
 *                       &lt;enumeration value="TimeWeeks"/>
 *                       &lt;enumeration value="TimeDays"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="hideMemberIf" default="Never">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="Never"/>
 *                       &lt;enumeration value="IfBlankName"/>
 *                       &lt;enumeration value="IfParentsName"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="formatter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="caption" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="captionColumn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MemberReaderParameter" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="hasAll" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="allMemberName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="allMemberCaption" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="allLevelName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="primaryKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="primaryKeyTable" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="defaultMember" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="memberReaderClass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="caption" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="uniqueKeyLevelName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Hierarchy", propOrder = {
    "annotations",
    "table",
    "view",
    "join",
    "inlineTable",
    "level",
    "memberReaderParameter"
})
public class Hierarchy {

    @XmlElement(name = "Annotations")
    protected Annotations annotations;
    @XmlElement(name = "Table")
    protected Table table;
    @XmlElement(name = "View")
    protected View view;
    @XmlElement(name = "Join")
    protected Hierarchy.Join join;
    @XmlElement(name = "InlineTable")
    protected Hierarchy.InlineTable inlineTable;
    @XmlElement(name = "Level", required = true)
    protected List<Hierarchy.Level> level;
    @XmlElement(name = "MemberReaderParameter")
    protected List<Hierarchy.MemberReaderParameter> memberReaderParameter;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "hasAll", required = true)
    protected boolean hasAll;
    @XmlAttribute(name = "allMemberName")
    protected String allMemberName;
    @XmlAttribute(name = "allMemberCaption")
    protected String allMemberCaption;
    @XmlAttribute(name = "allLevelName")
    protected String allLevelName;
    @XmlAttribute(name = "primaryKey")
    protected String primaryKey;
    @XmlAttribute(name = "primaryKeyTable")
    protected String primaryKeyTable;
    @XmlAttribute(name = "defaultMember")
    protected String defaultMember;
    @XmlAttribute(name = "memberReaderClass")
    protected String memberReaderClass;
    @XmlAttribute(name = "caption")
    protected String caption;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "uniqueKeyLevelName")
    protected String uniqueKeyLevelName;

    /**
     * Gets the value of the annotations property.
     * 
     * @return
     *     possible object is
     *     {@link Annotations }
     *     
     */
    public Annotations getAnnotations() {
        return annotations;
    }

    /**
     * Sets the value of the annotations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Annotations }
     *     
     */
    public void setAnnotations(Annotations value) {
        this.annotations = value;
    }

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link Table }
     *     
     */
    public Table getTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link Table }
     *     
     */
    public void setTable(Table value) {
        this.table = value;
    }

    /**
     * Gets the value of the view property.
     * 
     * @return
     *     possible object is
     *     {@link View }
     *     
     */
    public View getView() {
        return view;
    }

    /**
     * Sets the value of the view property.
     * 
     * @param value
     *     allowed object is
     *     {@link View }
     *     
     */
    public void setView(View value) {
        this.view = value;
    }

    /**
     * Gets the value of the join property.
     * 
     * @return
     *     possible object is
     *     {@link Hierarchy.Join }
     *     
     */
    public Hierarchy.Join getJoin() {
        return join;
    }

    /**
     * Sets the value of the join property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hierarchy.Join }
     *     
     */
    public void setJoin(Hierarchy.Join value) {
        this.join = value;
    }

    /**
     * Gets the value of the inlineTable property.
     * 
     * @return
     *     possible object is
     *     {@link Hierarchy.InlineTable }
     *     
     */
    public Hierarchy.InlineTable getInlineTable() {
        return inlineTable;
    }

    /**
     * Sets the value of the inlineTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hierarchy.InlineTable }
     *     
     */
    public void setInlineTable(Hierarchy.InlineTable value) {
        this.inlineTable = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the level property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLevel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Hierarchy.Level }
     * 
     * 
     */
    public List<Hierarchy.Level> getLevel() {
        if (level == null) {
            level = new ArrayList<Hierarchy.Level>();
        }
        return this.level;
    }

    /**
     * Gets the value of the memberReaderParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the memberReaderParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMemberReaderParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Hierarchy.MemberReaderParameter }
     * 
     * 
     */
    public List<Hierarchy.MemberReaderParameter> getMemberReaderParameter() {
        if (memberReaderParameter == null) {
            memberReaderParameter = new ArrayList<Hierarchy.MemberReaderParameter>();
        }
        return this.memberReaderParameter;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the hasAll property.
     * 
     */
    public boolean isHasAll() {
        return hasAll;
    }

    /**
     * Sets the value of the hasAll property.
     * 
     */
    public void setHasAll(boolean value) {
        this.hasAll = value;
    }

    /**
     * Gets the value of the allMemberName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllMemberName() {
        return allMemberName;
    }

    /**
     * Sets the value of the allMemberName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllMemberName(String value) {
        this.allMemberName = value;
    }

    /**
     * Gets the value of the allMemberCaption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllMemberCaption() {
        return allMemberCaption;
    }

    /**
     * Sets the value of the allMemberCaption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllMemberCaption(String value) {
        this.allMemberCaption = value;
    }

    /**
     * Gets the value of the allLevelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllLevelName() {
        return allLevelName;
    }

    /**
     * Sets the value of the allLevelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllLevelName(String value) {
        this.allLevelName = value;
    }

    /**
     * Gets the value of the primaryKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryKey() {
        return primaryKey;
    }

    /**
     * Sets the value of the primaryKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryKey(String value) {
        this.primaryKey = value;
    }

    /**
     * Gets the value of the primaryKeyTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryKeyTable() {
        return primaryKeyTable;
    }

    /**
     * Sets the value of the primaryKeyTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryKeyTable(String value) {
        this.primaryKeyTable = value;
    }

    /**
     * Gets the value of the defaultMember property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultMember() {
        return defaultMember;
    }

    /**
     * Sets the value of the defaultMember property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultMember(String value) {
        this.defaultMember = value;
    }

    /**
     * Gets the value of the memberReaderClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberReaderClass() {
        return memberReaderClass;
    }

    /**
     * Sets the value of the memberReaderClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberReaderClass(String value) {
        this.memberReaderClass = value;
    }

    /**
     * Gets the value of the caption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaption() {
        return caption;
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaption(String value) {
        this.caption = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the uniqueKeyLevelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueKeyLevelName() {
        return uniqueKeyLevelName;
    }

    /**
     * Sets the value of the uniqueKeyLevelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueKeyLevelName(String value) {
        this.uniqueKeyLevelName = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ColumnDefs">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ColumnDef" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="type">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="String"/>
     *                                 &lt;enumeration value="Numeric"/>
     *                                 &lt;enumeration value="Integer"/>
     *                                 &lt;enumeration value="Boolean"/>
     *                                 &lt;enumeration value="Date"/>
     *                                 &lt;enumeration value="Time"/>
     *                                 &lt;enumeration value="Timestamp"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Rows">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Row" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Value" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "columnDefs",
        "rows"
    })
    public static class InlineTable {

        @XmlElement(name = "ColumnDefs", required = true)
        protected Hierarchy.InlineTable.ColumnDefs columnDefs;
        @XmlElement(name = "Rows", required = true)
        protected Hierarchy.InlineTable.Rows rows;

        /**
         * Gets the value of the columnDefs property.
         * 
         * @return
         *     possible object is
         *     {@link Hierarchy.InlineTable.ColumnDefs }
         *     
         */
        public Hierarchy.InlineTable.ColumnDefs getColumnDefs() {
            return columnDefs;
        }

        /**
         * Sets the value of the columnDefs property.
         * 
         * @param value
         *     allowed object is
         *     {@link Hierarchy.InlineTable.ColumnDefs }
         *     
         */
        public void setColumnDefs(Hierarchy.InlineTable.ColumnDefs value) {
            this.columnDefs = value;
        }

        /**
         * Gets the value of the rows property.
         * 
         * @return
         *     possible object is
         *     {@link Hierarchy.InlineTable.Rows }
         *     
         */
        public Hierarchy.InlineTable.Rows getRows() {
            return rows;
        }

        /**
         * Sets the value of the rows property.
         * 
         * @param value
         *     allowed object is
         *     {@link Hierarchy.InlineTable.Rows }
         *     
         */
        public void setRows(Hierarchy.InlineTable.Rows value) {
            this.rows = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ColumnDef" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="type">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="String"/>
         *                       &lt;enumeration value="Numeric"/>
         *                       &lt;enumeration value="Integer"/>
         *                       &lt;enumeration value="Boolean"/>
         *                       &lt;enumeration value="Date"/>
         *                       &lt;enumeration value="Time"/>
         *                       &lt;enumeration value="Timestamp"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "columnDef"
        })
        public static class ColumnDefs {

            @XmlElement(name = "ColumnDef", required = true)
            protected List<Hierarchy.InlineTable.ColumnDefs.ColumnDef> columnDef;

            /**
             * Gets the value of the columnDef property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the columnDef property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getColumnDef().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Hierarchy.InlineTable.ColumnDefs.ColumnDef }
             * 
             * 
             */
            public List<Hierarchy.InlineTable.ColumnDefs.ColumnDef> getColumnDef() {
                if (columnDef == null) {
                    columnDef = new ArrayList<Hierarchy.InlineTable.ColumnDefs.ColumnDef>();
                }
                return this.columnDef;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="type">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="String"/>
             *             &lt;enumeration value="Numeric"/>
             *             &lt;enumeration value="Integer"/>
             *             &lt;enumeration value="Boolean"/>
             *             &lt;enumeration value="Date"/>
             *             &lt;enumeration value="Time"/>
             *             &lt;enumeration value="Timestamp"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class ColumnDef {

                @XmlAttribute(name = "name")
                protected String name;
                @XmlAttribute(name = "type")
                protected String type;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Row" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Value" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "row"
        })
        public static class Rows {

            @XmlElement(name = "Row", required = true)
            protected List<Hierarchy.InlineTable.Rows.Row> row;

            /**
             * Gets the value of the row property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the row property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRow().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Hierarchy.InlineTable.Rows.Row }
             * 
             * 
             */
            public List<Hierarchy.InlineTable.Rows.Row> getRow() {
                if (row == null) {
                    row = new ArrayList<Hierarchy.InlineTable.Rows.Row>();
                }
                return this.row;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Value" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Row {

                @XmlElement(name = "Value", required = true)
                protected List<Hierarchy.InlineTable.Rows.Row.Value> value;

                /**
                 * Gets the value of the value property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the value property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getValue().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Hierarchy.InlineTable.Rows.Row.Value }
                 * 
                 * 
                 */
                public List<Hierarchy.InlineTable.Rows.Row.Value> getValue() {
                    if (value == null) {
                        value = new ArrayList<Hierarchy.InlineTable.Rows.Row.Value>();
                    }
                    return this.value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "content"
                })
                public static class Value {

                    @XmlValue
                    protected String content;
                    @XmlAttribute(name = "column")
                    protected String column;

                    /**
                     * Gets the value of the content property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getContent() {
                        return content;
                    }

                    /**
                     * Sets the value of the content property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setContent(String value) {
                        this.content = value;
                    }

                    /**
                     * Gets the value of the column property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getColumn() {
                        return column;
                    }

                    /**
                     * Sets the value of the column property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setColumn(String value) {
                        this.column = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{}Relation" maxOccurs="2" minOccurs="2"/>
     *       &lt;/sequence>
     *       &lt;attribute name="leftAlias" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="leftKey" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="rightAlias" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="rightKey" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "relation"
    })
    public static class Join {

        @XmlElements({
            @XmlElement(name = "Table", type = Table.class),
            @XmlElement(name = "View", type = View.class),
            @XmlElement(name = "Join", type = Hierarchy.Join.class),
            @XmlElement(name = "InlineTable", type = Hierarchy.InlineTable.class)
        })
        protected List<Object> relation;
        @XmlAttribute(name = "leftAlias")
        protected String leftAlias;
        @XmlAttribute(name = "leftKey")
        protected String leftKey;
        @XmlAttribute(name = "rightAlias")
        protected String rightAlias;
        @XmlAttribute(name = "rightKey")
        protected String rightKey;

        /**
         * Gets the value of the relation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the relation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRelation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Table }
         * {@link View }
         * {@link Hierarchy.Join }
         * {@link Hierarchy.InlineTable }
         * 
         * 
         */
        public List<Object> getRelation() {
            if (relation == null) {
                relation = new ArrayList<Object>();
            }
            return this.relation;
        }

        /**
         * Gets the value of the leftAlias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLeftAlias() {
            return leftAlias;
        }

        /**
         * Sets the value of the leftAlias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLeftAlias(String value) {
            this.leftAlias = value;
        }

        /**
         * Gets the value of the leftKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLeftKey() {
            return leftKey;
        }

        /**
         * Sets the value of the leftKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLeftKey(String value) {
            this.leftKey = value;
        }

        /**
         * Gets the value of the rightAlias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRightAlias() {
            return rightAlias;
        }

        /**
         * Sets the value of the rightAlias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRightAlias(String value) {
            this.rightAlias = value;
        }

        /**
         * Gets the value of the rightKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRightKey() {
            return rightKey;
        }

        /**
         * Sets the value of the rightKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRightKey(String value) {
            this.rightKey = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Annotations" type="{}Annotations" minOccurs="0"/>
     *         &lt;element name="KeyExpression" type="{}ExpressionView" minOccurs="0"/>
     *         &lt;element name="NameExpression" type="{}ExpressionView" minOccurs="0"/>
     *         &lt;element name="CaptionExpression" type="{}ExpressionView" minOccurs="0"/>
     *         &lt;element name="OrdinalExpression" type="{}ExpressionView" minOccurs="0"/>
     *         &lt;element name="ParentExpression" type="{}ExpressionView" minOccurs="0"/>
     *         &lt;element name="Closure" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Table" type="{}Table"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="parentColumn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="childColumn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Property" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="column" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="type" default="String">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="String"/>
     *                       &lt;enumeration value="Numeric"/>
     *                       &lt;enumeration value="Integer"/>
     *                       &lt;enumeration value="Boolean"/>
     *                       &lt;enumeration value="Date"/>
     *                       &lt;enumeration value="Time"/>
     *                       &lt;enumeration value="Timestamp"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="formatter" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="caption" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="dependsOnLevelValue" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="approxRowCount" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="table" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="nameColumn" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ordinalColumn" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="parentColumn" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="nullParentValue" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="type">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="String"/>
     *             &lt;enumeration value="Numeric"/>
     *             &lt;enumeration value="Integer"/>
     *             &lt;enumeration value="Boolean"/>
     *             &lt;enumeration value="Date"/>
     *             &lt;enumeration value="Time"/>
     *             &lt;enumeration value="Timestamp"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="uniqueMembers" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *       &lt;attribute name="levelType" default="Regular">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="Regular"/>
     *             &lt;enumeration value="TimeYears"/>
     *             &lt;enumeration value="TimeQuarters"/>
     *             &lt;enumeration value="TimeMonths"/>
     *             &lt;enumeration value="TimeWeeks"/>
     *             &lt;enumeration value="TimeDays"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="hideMemberIf" default="Never">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="Never"/>
     *             &lt;enumeration value="IfBlankName"/>
     *             &lt;enumeration value="IfParentsName"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="formatter" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="caption" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="captionColumn" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "annotations",
        "keyExpression",
        "nameExpression",
        "captionExpression",
        "ordinalExpression",
        "parentExpression",
        "closure",
        "property"
    })
    public static class Level {

        @XmlElement(name = "Annotations")
        protected Annotations annotations;
        @XmlElement(name = "KeyExpression")
        protected ExpressionView keyExpression;
        @XmlElement(name = "NameExpression")
        protected ExpressionView nameExpression;
        @XmlElement(name = "CaptionExpression")
        protected ExpressionView captionExpression;
        @XmlElement(name = "OrdinalExpression")
        protected ExpressionView ordinalExpression;
        @XmlElement(name = "ParentExpression")
        protected ExpressionView parentExpression;
        @XmlElement(name = "Closure")
        protected Hierarchy.Level.Closure closure;
        @XmlElement(name = "Property")
        protected List<Hierarchy.Level.Property> property;
        @XmlAttribute(name = "approxRowCount")
        protected BigInteger approxRowCount;
        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "table")
        protected String table;
        @XmlAttribute(name = "column")
        protected String column;
        @XmlAttribute(name = "nameColumn")
        protected String nameColumn;
        @XmlAttribute(name = "ordinalColumn")
        protected String ordinalColumn;
        @XmlAttribute(name = "parentColumn")
        protected String parentColumn;
        @XmlAttribute(name = "nullParentValue")
        protected String nullParentValue;
        @XmlAttribute(name = "type")
        protected String type;
        @XmlAttribute(name = "uniqueMembers")
        protected Boolean uniqueMembers;
        @XmlAttribute(name = "levelType")
        protected String levelType;
        @XmlAttribute(name = "hideMemberIf")
        protected String hideMemberIf;
        @XmlAttribute(name = "formatter")
        protected String formatter;
        @XmlAttribute(name = "caption")
        protected String caption;
        @XmlAttribute(name = "description")
        protected String description;
        @XmlAttribute(name = "captionColumn")
        protected String captionColumn;

        /**
         * Gets the value of the annotations property.
         * 
         * @return
         *     possible object is
         *     {@link Annotations }
         *     
         */
        public Annotations getAnnotations() {
            return annotations;
        }

        /**
         * Sets the value of the annotations property.
         * 
         * @param value
         *     allowed object is
         *     {@link Annotations }
         *     
         */
        public void setAnnotations(Annotations value) {
            this.annotations = value;
        }

        /**
         * Gets the value of the keyExpression property.
         * 
         * @return
         *     possible object is
         *     {@link ExpressionView }
         *     
         */
        public ExpressionView getKeyExpression() {
            return keyExpression;
        }

        /**
         * Sets the value of the keyExpression property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExpressionView }
         *     
         */
        public void setKeyExpression(ExpressionView value) {
            this.keyExpression = value;
        }

        /**
         * Gets the value of the nameExpression property.
         * 
         * @return
         *     possible object is
         *     {@link ExpressionView }
         *     
         */
        public ExpressionView getNameExpression() {
            return nameExpression;
        }

        /**
         * Sets the value of the nameExpression property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExpressionView }
         *     
         */
        public void setNameExpression(ExpressionView value) {
            this.nameExpression = value;
        }

        /**
         * Gets the value of the captionExpression property.
         * 
         * @return
         *     possible object is
         *     {@link ExpressionView }
         *     
         */
        public ExpressionView getCaptionExpression() {
            return captionExpression;
        }

        /**
         * Sets the value of the captionExpression property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExpressionView }
         *     
         */
        public void setCaptionExpression(ExpressionView value) {
            this.captionExpression = value;
        }

        /**
         * Gets the value of the ordinalExpression property.
         * 
         * @return
         *     possible object is
         *     {@link ExpressionView }
         *     
         */
        public ExpressionView getOrdinalExpression() {
            return ordinalExpression;
        }

        /**
         * Sets the value of the ordinalExpression property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExpressionView }
         *     
         */
        public void setOrdinalExpression(ExpressionView value) {
            this.ordinalExpression = value;
        }

        /**
         * Gets the value of the parentExpression property.
         * 
         * @return
         *     possible object is
         *     {@link ExpressionView }
         *     
         */
        public ExpressionView getParentExpression() {
            return parentExpression;
        }

        /**
         * Sets the value of the parentExpression property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExpressionView }
         *     
         */
        public void setParentExpression(ExpressionView value) {
            this.parentExpression = value;
        }

        /**
         * Gets the value of the closure property.
         * 
         * @return
         *     possible object is
         *     {@link Hierarchy.Level.Closure }
         *     
         */
        public Hierarchy.Level.Closure getClosure() {
            return closure;
        }

        /**
         * Sets the value of the closure property.
         * 
         * @param value
         *     allowed object is
         *     {@link Hierarchy.Level.Closure }
         *     
         */
        public void setClosure(Hierarchy.Level.Closure value) {
            this.closure = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the property property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProperty().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Hierarchy.Level.Property }
         * 
         * 
         */
        public List<Hierarchy.Level.Property> getProperty() {
            if (property == null) {
                property = new ArrayList<Hierarchy.Level.Property>();
            }
            return this.property;
        }

        /**
         * Gets the value of the approxRowCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getApproxRowCount() {
            return approxRowCount;
        }

        /**
         * Sets the value of the approxRowCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setApproxRowCount(BigInteger value) {
            this.approxRowCount = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the table property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTable() {
            return table;
        }

        /**
         * Sets the value of the table property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTable(String value) {
            this.table = value;
        }

        /**
         * Gets the value of the column property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getColumn() {
            return column;
        }

        /**
         * Sets the value of the column property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setColumn(String value) {
            this.column = value;
        }

        /**
         * Gets the value of the nameColumn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNameColumn() {
            return nameColumn;
        }

        /**
         * Sets the value of the nameColumn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNameColumn(String value) {
            this.nameColumn = value;
        }

        /**
         * Gets the value of the ordinalColumn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrdinalColumn() {
            return ordinalColumn;
        }

        /**
         * Sets the value of the ordinalColumn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrdinalColumn(String value) {
            this.ordinalColumn = value;
        }

        /**
         * Gets the value of the parentColumn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParentColumn() {
            return parentColumn;
        }

        /**
         * Sets the value of the parentColumn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParentColumn(String value) {
            this.parentColumn = value;
        }

        /**
         * Gets the value of the nullParentValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNullParentValue() {
            return nullParentValue;
        }

        /**
         * Sets the value of the nullParentValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNullParentValue(String value) {
            this.nullParentValue = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the uniqueMembers property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isUniqueMembers() {
            if (uniqueMembers == null) {
                return false;
            } else {
                return uniqueMembers;
            }
        }

        /**
         * Sets the value of the uniqueMembers property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setUniqueMembers(Boolean value) {
            this.uniqueMembers = value;
        }

        /**
         * Gets the value of the levelType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLevelType() {
            if (levelType == null) {
                return "Regular";
            } else {
                return levelType;
            }
        }

        /**
         * Sets the value of the levelType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLevelType(String value) {
            this.levelType = value;
        }

        /**
         * Gets the value of the hideMemberIf property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHideMemberIf() {
            if (hideMemberIf == null) {
                return "Never";
            } else {
                return hideMemberIf;
            }
        }

        /**
         * Sets the value of the hideMemberIf property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHideMemberIf(String value) {
            this.hideMemberIf = value;
        }

        /**
         * Gets the value of the formatter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormatter() {
            return formatter;
        }

        /**
         * Sets the value of the formatter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormatter(String value) {
            this.formatter = value;
        }

        /**
         * Gets the value of the caption property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCaption() {
            return caption;
        }

        /**
         * Sets the value of the caption property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCaption(String value) {
            this.caption = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the captionColumn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCaptionColumn() {
            return captionColumn;
        }

        /**
         * Sets the value of the captionColumn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCaptionColumn(String value) {
            this.captionColumn = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Table" type="{}Table"/>
         *       &lt;/sequence>
         *       &lt;attribute name="parentColumn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="childColumn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "table"
        })
        public static class Closure {

            @XmlElement(name = "Table", required = true)
            protected Table table;
            @XmlAttribute(name = "parentColumn", required = true)
            protected String parentColumn;
            @XmlAttribute(name = "childColumn", required = true)
            protected String childColumn;

            /**
             * Gets the value of the table property.
             * 
             * @return
             *     possible object is
             *     {@link Table }
             *     
             */
            public Table getTable() {
                return table;
            }

            /**
             * Sets the value of the table property.
             * 
             * @param value
             *     allowed object is
             *     {@link Table }
             *     
             */
            public void setTable(Table value) {
                this.table = value;
            }

            /**
             * Gets the value of the parentColumn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getParentColumn() {
                return parentColumn;
            }

            /**
             * Sets the value of the parentColumn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setParentColumn(String value) {
                this.parentColumn = value;
            }

            /**
             * Gets the value of the childColumn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChildColumn() {
                return childColumn;
            }

            /**
             * Sets the value of the childColumn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChildColumn(String value) {
                this.childColumn = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="column" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="type" default="String">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="String"/>
         *             &lt;enumeration value="Numeric"/>
         *             &lt;enumeration value="Integer"/>
         *             &lt;enumeration value="Boolean"/>
         *             &lt;enumeration value="Date"/>
         *             &lt;enumeration value="Time"/>
         *             &lt;enumeration value="Timestamp"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="formatter" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="caption" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="dependsOnLevelValue" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Property {

            @XmlAttribute(name = "name", required = true)
            protected String name;
            @XmlAttribute(name = "column", required = true)
            protected String column;
            @XmlAttribute(name = "type")
            protected String type;
            @XmlAttribute(name = "formatter")
            protected String formatter;
            @XmlAttribute(name = "caption")
            protected String caption;
            @XmlAttribute(name = "description")
            protected String description;
            @XmlAttribute(name = "dependsOnLevelValue")
            protected Boolean dependsOnLevelValue;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the column property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getColumn() {
                return column;
            }

            /**
             * Sets the value of the column property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setColumn(String value) {
                this.column = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                if (type == null) {
                    return "String";
                } else {
                    return type;
                }
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the formatter property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFormatter() {
                return formatter;
            }

            /**
             * Sets the value of the formatter property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFormatter(String value) {
                this.formatter = value;
            }

            /**
             * Gets the value of the caption property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCaption() {
                return caption;
            }

            /**
             * Sets the value of the caption property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCaption(String value) {
                this.caption = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the dependsOnLevelValue property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isDependsOnLevelValue() {
                if (dependsOnLevelValue == null) {
                    return false;
                } else {
                    return dependsOnLevelValue;
                }
            }

            /**
             * Sets the value of the dependsOnLevelValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setDependsOnLevelValue(Boolean value) {
                this.dependsOnLevelValue = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class MemberReaderParameter {

        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "value", required = true)
        protected String value;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
