//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.26 at 10:48:45 AM CEST 
//


package org.openforis.collect.mondrian;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openforis.calc.mondrian package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openforis.calc.mondrian
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Annotations.Annotation }
     * 
     */
    public Annotations.Annotation createAnnotationsAnnotation() {
        return new Annotations.Annotation();
    }

    /**
     * Create an instance of {@link SQL }
     * 
     */
    public SQL createSQL() {
        return new SQL();
    }

    /**
     * Create an instance of {@link Schema.Cube }
     * 
     */
    public Schema.Cube createSchemaCube() {
        return new Schema.Cube();
    }

    /**
     * Create an instance of {@link Hierarchy.InlineTable.ColumnDefs }
     * 
     */
    public Hierarchy.InlineTable.ColumnDefs createHierarchyInlineTableColumnDefs() {
        return new Hierarchy.InlineTable.ColumnDefs();
    }

    /**
     * Create an instance of {@link Hierarchy.InlineTable.ColumnDefs.ColumnDef }
     * 
     */
    public Hierarchy.InlineTable.ColumnDefs.ColumnDef createHierarchyInlineTableColumnDefsColumnDef() {
        return new Hierarchy.InlineTable.ColumnDefs.ColumnDef();
    }

    /**
     * Create an instance of {@link CalculatedMember }
     * 
     */
    public CalculatedMember createCalculatedMember() {
        return new CalculatedMember();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link Table.AggName }
     * 
     */
    public Table.AggName createTableAggName() {
        return new Table.AggName();
    }

    /**
     * Create an instance of {@link Schema.Role.SchemaGrant.CubeGrant.DimensionGrant }
     * 
     */
    public Schema.Role.SchemaGrant.CubeGrant.DimensionGrant createSchemaRoleSchemaGrantCubeGrantDimensionGrant() {
        return new Schema.Role.SchemaGrant.CubeGrant.DimensionGrant();
    }

    /**
     * Create an instance of {@link Table.AggPattern.AggLevel }
     * 
     */
    public Table.AggPattern.AggLevel createTableAggPatternAggLevel() {
        return new Table.AggPattern.AggLevel();
    }

    /**
     * Create an instance of {@link Table.AggPattern.AggExclude }
     * 
     */
    public Table.AggPattern.AggExclude createTableAggPatternAggExclude() {
        return new Table.AggPattern.AggExclude();
    }

    /**
     * Create an instance of {@link Schema.Role.SchemaGrant.CubeGrant.HierarchyGrant }
     * 
     */
    public Schema.Role.SchemaGrant.CubeGrant.HierarchyGrant createSchemaRoleSchemaGrantCubeGrantHierarchyGrant() {
        return new Schema.Role.SchemaGrant.CubeGrant.HierarchyGrant();
    }

    /**
     * Create an instance of {@link Hierarchy.InlineTable.Rows }
     * 
     */
    public Hierarchy.InlineTable.Rows createHierarchyInlineTableRows() {
        return new Hierarchy.InlineTable.Rows();
    }

    /**
     * Create an instance of {@link Schema.Role.SchemaGrant }
     * 
     */
    public Schema.Role.SchemaGrant createSchemaRoleSchemaGrant() {
        return new Schema.Role.SchemaGrant();
    }

    /**
     * Create an instance of {@link Hierarchy.Level.Property }
     * 
     */
    public Hierarchy.Level.Property createHierarchyLevelProperty() {
        return new Hierarchy.Level.Property();
    }

    /**
     * Create an instance of {@link ExpressionView }
     * 
     */
    public ExpressionView createExpressionView() {
        return new ExpressionView();
    }

    /**
     * Create an instance of {@link Hierarchy.InlineTable }
     * 
     */
    public Hierarchy.InlineTable createHierarchyInlineTable() {
        return new Hierarchy.InlineTable();
    }

    /**
     * Create an instance of {@link Table.AggPattern }
     * 
     */
    public Table.AggPattern createTableAggPattern() {
        return new Table.AggPattern();
    }

    /**
     * Create an instance of {@link Schema.Role.Union.RoleUsage }
     * 
     */
    public Schema.Role.Union.RoleUsage createSchemaRoleUnionRoleUsage() {
        return new Schema.Role.Union.RoleUsage();
    }

    /**
     * Create an instance of {@link Hierarchy.InlineTable.Rows.Row.Value }
     * 
     */
    public Hierarchy.InlineTable.Rows.Row.Value createHierarchyInlineTableRowsRowValue() {
        return new Hierarchy.InlineTable.Rows.Row.Value();
    }

    /**
     * Create an instance of {@link Hierarchy }
     * 
     */
    public Hierarchy createHierarchy() {
        return new Hierarchy();
    }

    /**
     * Create an instance of {@link Schema.VirtualCube.VirtualCubeDimension }
     * 
     */
    public Schema.VirtualCube.VirtualCubeDimension createSchemaVirtualCubeVirtualCubeDimension() {
        return new Schema.VirtualCube.VirtualCubeDimension();
    }

    /**
     * Create an instance of {@link Schema.Role.SchemaGrant.CubeGrant }
     * 
     */
    public Schema.Role.SchemaGrant.CubeGrant createSchemaRoleSchemaGrantCubeGrant() {
        return new Schema.Role.SchemaGrant.CubeGrant();
    }

    /**
     * Create an instance of {@link SharedDimension }
     * 
     */
    public SharedDimension createSharedDimension() {
        return new SharedDimension();
    }

    /**
     * Create an instance of {@link Table.AggName.AggForeignKey }
     * 
     */
    public Table.AggName.AggForeignKey createTableAggNameAggForeignKey() {
        return new Table.AggName.AggForeignKey();
    }

    /**
     * Create an instance of {@link Schema.VirtualCube.CubeUsages }
     * 
     */
    public Schema.VirtualCube.CubeUsages createSchemaVirtualCubeCubeUsages() {
        return new Schema.VirtualCube.CubeUsages();
    }

    /**
     * Create an instance of {@link Schema.Role.Union }
     * 
     */
    public Schema.Role.Union createSchemaRoleUnion() {
        return new Schema.Role.Union();
    }

    /**
     * Create an instance of {@link Table.AggPattern.AggMeasure }
     * 
     */
    public Table.AggPattern.AggMeasure createTableAggPatternAggMeasure() {
        return new Table.AggPattern.AggMeasure();
    }

    /**
     * Create an instance of {@link View }
     * 
     */
    public View createView() {
        return new View();
    }

    /**
     * Create an instance of {@link CalculatedMemberProperty }
     * 
     */
    public CalculatedMemberProperty createCalculatedMemberProperty() {
        return new CalculatedMemberProperty();
    }

    /**
     * Create an instance of {@link AggColumnName }
     * 
     */
    public AggColumnName createAggColumnName() {
        return new AggColumnName();
    }

    /**
     * Create an instance of {@link Hierarchy.Level }
     * 
     */
    public Hierarchy.Level createHierarchyLevel() {
        return new Hierarchy.Level();
    }

    /**
     * Create an instance of {@link Table.Hint }
     * 
     */
    public Table.Hint createTableHint() {
        return new Table.Hint();
    }

    /**
     * Create an instance of {@link NamedSet }
     * 
     */
    public NamedSet createNamedSet() {
        return new NamedSet();
    }

    /**
     * Create an instance of {@link Hierarchy.Level.Closure }
     * 
     */
    public Hierarchy.Level.Closure createHierarchyLevelClosure() {
        return new Hierarchy.Level.Closure();
    }

    /**
     * Create an instance of {@link Schema }
     * 
     */
    public Schema createSchema() {
        return new Schema();
    }

    /**
     * Create an instance of {@link DimensionUsage }
     * 
     */
    public DimensionUsage createDimensionUsage() {
        return new DimensionUsage();
    }

    /**
     * Create an instance of {@link Table.AggPattern.AggForeignKey }
     * 
     */
    public Table.AggPattern.AggForeignKey createTableAggPatternAggForeignKey() {
        return new Table.AggPattern.AggForeignKey();
    }

    /**
     * Create an instance of {@link Table.AggName.AggMeasure }
     * 
     */
    public Table.AggName.AggMeasure createTableAggNameAggMeasure() {
        return new Table.AggName.AggMeasure();
    }

    /**
     * Create an instance of {@link Schema.Cube.Measure }
     * 
     */
    public Schema.Cube.Measure createSchemaCubeMeasure() {
        return new Schema.Cube.Measure();
    }

    /**
     * Create an instance of {@link Schema.Parameter }
     * 
     */
    public Schema.Parameter createSchemaParameter() {
        return new Schema.Parameter();
    }

    /**
     * Create an instance of {@link Schema.VirtualCube.VirtualCubeMeasure }
     * 
     */
    public Schema.VirtualCube.VirtualCubeMeasure createSchemaVirtualCubeVirtualCubeMeasure() {
        return new Schema.VirtualCube.VirtualCubeMeasure();
    }

    /**
     * Create an instance of {@link Schema.VirtualCube }
     * 
     */
    public Schema.VirtualCube createSchemaVirtualCube() {
        return new Schema.VirtualCube();
    }

    /**
     * Create an instance of {@link Schema.VirtualCube.CubeUsages.CubeUsage }
     * 
     */
    public Schema.VirtualCube.CubeUsages.CubeUsage createSchemaVirtualCubeCubeUsagesCubeUsage() {
        return new Schema.VirtualCube.CubeUsages.CubeUsage();
    }

    /**
     * Create an instance of {@link Hierarchy.MemberReaderParameter }
     * 
     */
    public Hierarchy.MemberReaderParameter createHierarchyMemberReaderParameter() {
        return new Hierarchy.MemberReaderParameter();
    }

    /**
     * Create an instance of {@link Hierarchy.Join }
     * 
     */
    public Hierarchy.Join createHierarchyJoin() {
        return new Hierarchy.Join();
    }

    /**
     * Create an instance of {@link Schema.Role }
     * 
     */
    public Schema.Role createSchemaRole() {
        return new Schema.Role();
    }

    /**
     * Create an instance of {@link Schema.Role.SchemaGrant.CubeGrant.HierarchyGrant.MemberGrant }
     * 
     */
    public Schema.Role.SchemaGrant.CubeGrant.HierarchyGrant.MemberGrant createSchemaRoleSchemaGrantCubeGrantHierarchyGrantMemberGrant() {
        return new Schema.Role.SchemaGrant.CubeGrant.HierarchyGrant.MemberGrant();
    }

    /**
     * Create an instance of {@link Annotations }
     * 
     */
    public Annotations createAnnotations() {
        return new Annotations();
    }

    /**
     * Create an instance of {@link PrivateDimension }
     * 
     */
    public PrivateDimension createPrivateDimension() {
        return new PrivateDimension();
    }

    /**
     * Create an instance of {@link Hierarchy.InlineTable.Rows.Row }
     * 
     */
    public Hierarchy.InlineTable.Rows.Row createHierarchyInlineTableRowsRow() {
        return new Hierarchy.InlineTable.Rows.Row();
    }

    /**
     * Create an instance of {@link Table.AggExclude }
     * 
     */
    public Table.AggExclude createTableAggExclude() {
        return new Table.AggExclude();
    }

    /**
     * Create an instance of {@link Schema.UserDefinedFunction }
     * 
     */
    public Schema.UserDefinedFunction createSchemaUserDefinedFunction() {
        return new Schema.UserDefinedFunction();
    }

    /**
     * Create an instance of {@link Table.AggName.AggLevel }
     * 
     */
    public Table.AggName.AggLevel createTableAggNameAggLevel() {
        return new Table.AggName.AggLevel();
    }

}
