//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.26 at 10:48:45 AM CEST 
//


package org.openforis.collect.mondrian;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for Table complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Table">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SQL" type="{}SQL" minOccurs="0"/>
 *         &lt;element name="AggExclude" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ignorecase" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;group ref="{}AggTable" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Hint" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="schema" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Table", propOrder = {
    "sql",
    "aggExclude",
    "aggTable",
    "hint"
})
public class Table {

    @XmlElement(name = "SQL")
    protected SQL sql;
    @XmlElement(name = "AggExclude")
    protected List<Table.AggExclude> aggExclude;
    @XmlElements({
        @XmlElement(name = "AggName", type = Table.AggName.class),
        @XmlElement(name = "AggPattern", type = Table.AggPattern.class)
    })
    protected List<Object> aggTable;
    @XmlElement(name = "Hint")
    protected List<Table.Hint> hint;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "schema")
    protected String schema;
    @XmlAttribute(name = "alias")
    protected String alias;

    /**
     * Gets the value of the sql property.
     * 
     * @return
     *     possible object is
     *     {@link SQL }
     *     
     */
    public SQL getSQL() {
        return sql;
    }

    /**
     * Sets the value of the sql property.
     * 
     * @param value
     *     allowed object is
     *     {@link SQL }
     *     
     */
    public void setSQL(SQL value) {
        this.sql = value;
    }

    /**
     * Gets the value of the aggExclude property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aggExclude property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAggExclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Table.AggExclude }
     * 
     * 
     */
    public List<Table.AggExclude> getAggExclude() {
        if (aggExclude == null) {
            aggExclude = new ArrayList<Table.AggExclude>();
        }
        return this.aggExclude;
    }

    /**
     * 
     *                         A definition of an aggregate table for a base fact table.
     *                         This aggregate table must be in the same schema as the base fact table. 
     *                     Gets the value of the aggTable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aggTable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAggTable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Table.AggName }
     * {@link Table.AggPattern }
     * 
     * 
     */
    public List<Object> getAggTable() {
        if (aggTable == null) {
            aggTable = new ArrayList<Object>();
        }
        return this.aggTable;
    }

    /**
     * Gets the value of the hint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Table.Hint }
     * 
     * 
     */
    public List<Table.Hint> getHint() {
        if (hint == null) {
            hint = new ArrayList<Table.Hint>();
        }
        return this.hint;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the schema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchema() {
        return schema;
    }

    /**
     * Sets the value of the schema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchema(String value) {
        this.schema = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ignorecase" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AggExclude {

        @XmlAttribute(name = "pattern")
        protected String pattern;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "ignorecase")
        protected Boolean ignorecase;

        /**
         * Gets the value of the pattern property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPattern() {
            return pattern;
        }

        /**
         * Sets the value of the pattern property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPattern(String value) {
            this.pattern = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the ignorecase property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isIgnorecase() {
            if (ignorecase == null) {
                return true;
            } else {
                return ignorecase;
            }
        }

        /**
         * Sets the value of the ignorecase property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setIgnorecase(Boolean value) {
            this.ignorecase = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AggFactCount" type="{}AggColumnName"/>
     *         &lt;element name="AggIgnoreColumn" type="{}AggColumnName" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="AggForeignKey" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="factColumn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="aggColumn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="AggMeasure" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="column" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="AggLevel" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="column" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ignorecase" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *       &lt;attribute name="approxRowCount" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "aggFactCount",
        "aggIgnoreColumn",
        "aggForeignKey",
        "aggMeasure",
        "aggLevel"
    })
    public static class AggName {

        @XmlElement(name = "AggFactCount", required = true)
        protected AggColumnName aggFactCount;
        @XmlElement(name = "AggIgnoreColumn")
        protected List<AggColumnName> aggIgnoreColumn;
        @XmlElement(name = "AggForeignKey")
        protected List<Table.AggName.AggForeignKey> aggForeignKey;
        @XmlElement(name = "AggMeasure", required = true)
        protected List<Table.AggName.AggMeasure> aggMeasure;
        @XmlElement(name = "AggLevel")
        protected List<Table.AggName.AggLevel> aggLevel;
        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "ignorecase")
        protected Boolean ignorecase;
        @XmlAttribute(name = "approxRowCount")
        protected BigInteger approxRowCount;

        /**
         * Gets the value of the aggFactCount property.
         * 
         * @return
         *     possible object is
         *     {@link AggColumnName }
         *     
         */
        public AggColumnName getAggFactCount() {
            return aggFactCount;
        }

        /**
         * Sets the value of the aggFactCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link AggColumnName }
         *     
         */
        public void setAggFactCount(AggColumnName value) {
            this.aggFactCount = value;
        }

        /**
         * Gets the value of the aggIgnoreColumn property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the aggIgnoreColumn property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAggIgnoreColumn().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AggColumnName }
         * 
         * 
         */
        public List<AggColumnName> getAggIgnoreColumn() {
            if (aggIgnoreColumn == null) {
                aggIgnoreColumn = new ArrayList<AggColumnName>();
            }
            return this.aggIgnoreColumn;
        }

        /**
         * Gets the value of the aggForeignKey property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the aggForeignKey property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAggForeignKey().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Table.AggName.AggForeignKey }
         * 
         * 
         */
        public List<Table.AggName.AggForeignKey> getAggForeignKey() {
            if (aggForeignKey == null) {
                aggForeignKey = new ArrayList<Table.AggName.AggForeignKey>();
            }
            return this.aggForeignKey;
        }

        /**
         * Gets the value of the aggMeasure property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the aggMeasure property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAggMeasure().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Table.AggName.AggMeasure }
         * 
         * 
         */
        public List<Table.AggName.AggMeasure> getAggMeasure() {
            if (aggMeasure == null) {
                aggMeasure = new ArrayList<Table.AggName.AggMeasure>();
            }
            return this.aggMeasure;
        }

        /**
         * Gets the value of the aggLevel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the aggLevel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAggLevel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Table.AggName.AggLevel }
         * 
         * 
         */
        public List<Table.AggName.AggLevel> getAggLevel() {
            if (aggLevel == null) {
                aggLevel = new ArrayList<Table.AggName.AggLevel>();
            }
            return this.aggLevel;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the ignorecase property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isIgnorecase() {
            if (ignorecase == null) {
                return true;
            } else {
                return ignorecase;
            }
        }

        /**
         * Sets the value of the ignorecase property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setIgnorecase(Boolean value) {
            this.ignorecase = value;
        }

        /**
         * Gets the value of the approxRowCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getApproxRowCount() {
            return approxRowCount;
        }

        /**
         * Sets the value of the approxRowCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setApproxRowCount(BigInteger value) {
            this.approxRowCount = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="factColumn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="aggColumn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class AggForeignKey {

            @XmlAttribute(name = "factColumn", required = true)
            protected String factColumn;
            @XmlAttribute(name = "aggColumn", required = true)
            protected String aggColumn;

            /**
             * Gets the value of the factColumn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFactColumn() {
                return factColumn;
            }

            /**
             * Sets the value of the factColumn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFactColumn(String value) {
                this.factColumn = value;
            }

            /**
             * Gets the value of the aggColumn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAggColumn() {
                return aggColumn;
            }

            /**
             * Sets the value of the aggColumn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAggColumn(String value) {
                this.aggColumn = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="column" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class AggLevel {

            @XmlAttribute(name = "column", required = true)
            protected String column;
            @XmlAttribute(name = "name", required = true)
            protected String name;

            /**
             * Gets the value of the column property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getColumn() {
                return column;
            }

            /**
             * Sets the value of the column property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setColumn(String value) {
                this.column = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="column" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class AggMeasure {

            @XmlAttribute(name = "column", required = true)
            protected String column;
            @XmlAttribute(name = "name", required = true)
            protected String name;

            /**
             * Gets the value of the column property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getColumn() {
                return column;
            }

            /**
             * Sets the value of the column property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setColumn(String value) {
                this.column = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AggFactCount" type="{}AggColumnName"/>
     *         &lt;element name="AggIgnoreColumn" type="{}AggColumnName" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="AggForeignKey" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="factColumn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="aggColumn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="AggMeasure" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="column" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="AggLevel" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="column" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="AggExclude" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ignorecase" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="pattern" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ignorecase" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "aggFactCount",
        "aggIgnoreColumn",
        "aggForeignKey",
        "aggMeasure",
        "aggLevel",
        "aggExclude"
    })
    public static class AggPattern {

        @XmlElement(name = "AggFactCount", required = true)
        protected AggColumnName aggFactCount;
        @XmlElement(name = "AggIgnoreColumn")
        protected List<AggColumnName> aggIgnoreColumn;
        @XmlElement(name = "AggForeignKey")
        protected List<Table.AggPattern.AggForeignKey> aggForeignKey;
        @XmlElement(name = "AggMeasure", required = true)
        protected List<Table.AggPattern.AggMeasure> aggMeasure;
        @XmlElement(name = "AggLevel")
        protected List<Table.AggPattern.AggLevel> aggLevel;
        @XmlElement(name = "AggExclude")
        protected List<Table.AggPattern.AggExclude> aggExclude;
        @XmlAttribute(name = "pattern", required = true)
        protected String pattern;
        @XmlAttribute(name = "ignorecase")
        protected Boolean ignorecase;

        /**
         * Gets the value of the aggFactCount property.
         * 
         * @return
         *     possible object is
         *     {@link AggColumnName }
         *     
         */
        public AggColumnName getAggFactCount() {
            return aggFactCount;
        }

        /**
         * Sets the value of the aggFactCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link AggColumnName }
         *     
         */
        public void setAggFactCount(AggColumnName value) {
            this.aggFactCount = value;
        }

        /**
         * Gets the value of the aggIgnoreColumn property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the aggIgnoreColumn property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAggIgnoreColumn().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AggColumnName }
         * 
         * 
         */
        public List<AggColumnName> getAggIgnoreColumn() {
            if (aggIgnoreColumn == null) {
                aggIgnoreColumn = new ArrayList<AggColumnName>();
            }
            return this.aggIgnoreColumn;
        }

        /**
         * Gets the value of the aggForeignKey property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the aggForeignKey property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAggForeignKey().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Table.AggPattern.AggForeignKey }
         * 
         * 
         */
        public List<Table.AggPattern.AggForeignKey> getAggForeignKey() {
            if (aggForeignKey == null) {
                aggForeignKey = new ArrayList<Table.AggPattern.AggForeignKey>();
            }
            return this.aggForeignKey;
        }

        /**
         * Gets the value of the aggMeasure property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the aggMeasure property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAggMeasure().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Table.AggPattern.AggMeasure }
         * 
         * 
         */
        public List<Table.AggPattern.AggMeasure> getAggMeasure() {
            if (aggMeasure == null) {
                aggMeasure = new ArrayList<Table.AggPattern.AggMeasure>();
            }
            return this.aggMeasure;
        }

        /**
         * Gets the value of the aggLevel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the aggLevel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAggLevel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Table.AggPattern.AggLevel }
         * 
         * 
         */
        public List<Table.AggPattern.AggLevel> getAggLevel() {
            if (aggLevel == null) {
                aggLevel = new ArrayList<Table.AggPattern.AggLevel>();
            }
            return this.aggLevel;
        }

        /**
         * Gets the value of the aggExclude property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the aggExclude property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAggExclude().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Table.AggPattern.AggExclude }
         * 
         * 
         */
        public List<Table.AggPattern.AggExclude> getAggExclude() {
            if (aggExclude == null) {
                aggExclude = new ArrayList<Table.AggPattern.AggExclude>();
            }
            return this.aggExclude;
        }

        /**
         * Gets the value of the pattern property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPattern() {
            return pattern;
        }

        /**
         * Sets the value of the pattern property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPattern(String value) {
            this.pattern = value;
        }

        /**
         * Gets the value of the ignorecase property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isIgnorecase() {
            if (ignorecase == null) {
                return true;
            } else {
                return ignorecase;
            }
        }

        /**
         * Sets the value of the ignorecase property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setIgnorecase(Boolean value) {
            this.ignorecase = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ignorecase" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class AggExclude {

            @XmlAttribute(name = "pattern")
            protected String pattern;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "ignorecase")
            protected Boolean ignorecase;

            /**
             * Gets the value of the pattern property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPattern() {
                return pattern;
            }

            /**
             * Sets the value of the pattern property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPattern(String value) {
                this.pattern = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the ignorecase property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isIgnorecase() {
                if (ignorecase == null) {
                    return true;
                } else {
                    return ignorecase;
                }
            }

            /**
             * Sets the value of the ignorecase property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setIgnorecase(Boolean value) {
                this.ignorecase = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="factColumn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="aggColumn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class AggForeignKey {

            @XmlAttribute(name = "factColumn", required = true)
            protected String factColumn;
            @XmlAttribute(name = "aggColumn", required = true)
            protected String aggColumn;

            /**
             * Gets the value of the factColumn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFactColumn() {
                return factColumn;
            }

            /**
             * Sets the value of the factColumn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFactColumn(String value) {
                this.factColumn = value;
            }

            /**
             * Gets the value of the aggColumn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAggColumn() {
                return aggColumn;
            }

            /**
             * Sets the value of the aggColumn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAggColumn(String value) {
                this.aggColumn = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="column" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class AggLevel {

            @XmlAttribute(name = "column", required = true)
            protected String column;
            @XmlAttribute(name = "name", required = true)
            protected String name;

            /**
             * Gets the value of the column property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getColumn() {
                return column;
            }

            /**
             * Sets the value of the column property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setColumn(String value) {
                this.column = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="column" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class AggMeasure {

            @XmlAttribute(name = "column", required = true)
            protected String column;
            @XmlAttribute(name = "name", required = true)
            protected String name;

            /**
             * Gets the value of the column property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getColumn() {
                return column;
            }

            /**
             * Sets the value of the column property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setColumn(String value) {
                this.column = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Hint {

        @XmlValue
        protected String content;
        @XmlAttribute(name = "type", required = true)
        protected String type;

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }

}
