/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openforis.idm.metamodel {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.openforis.idm.metamodel.CodingScheme$CodeType")]
    public class CodingScheme$CodeType extends Enum {

        public static const NUMERIC:CodingScheme$CodeType = new CodingScheme$CodeType("NUMERIC", _);
        public static const ALPHANUMERIC:CodingScheme$CodeType = new CodingScheme$CodeType("ALPHANUMERIC", _);

        function CodingScheme$CodeType(value:String = null, restrictor:* = null) {
            super((value || NUMERIC.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [NUMERIC, ALPHANUMERIC];
        }

        public static function valueOf(name:String):CodingScheme$CodeType {
            return CodingScheme$CodeType(NUMERIC.constantOf(name));
        }
    }
}