/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openforis.idm.metamodel {

    public interface FileAttributeDefinition extends AttributeDefinition {

        function get extensions():Array;

        function get maxSize():Number;
    }
}