/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openforis.idm.metamodel {

    import mx.collections.ListCollectionView;

    public interface ModelObjectDefinition extends Versionable, Annotatable, ModelObjectDefinitionContainer {

        function get cardinality():Cardinality;

        function get descriptions():ListCollectionView;

        function get labels():ListCollectionView;

        function get multiple():Boolean;

        function get name():String;

        function get parentDefinition():EntityDefinition;

        function get relevantExpression():String;
    }
}