/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openforis.idm.metamodel {

    import mx.collections.ListCollectionView;
    
    public interface Survey {

        function get codeLists():ListCollectionView;

        function get configuration():XML;

        function get cycle():Number;

        function get descriptions():ListCollectionView;

        function get name():String;

        function get projectNames():ListCollectionView;

        function get schema():Schema;

        function get spatialReferenceSystems():ListCollectionView;

        function get units():ListCollectionView;

        function get versions():ListCollectionView;
    }
}