/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openforis.idm.metamodel {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.openforis.idm.metamodel.TextAttributeDefinition$Type")]
    public class TextAttributeDefinition$Type extends Enum {

        public static const SHORT:TextAttributeDefinition$Type = new TextAttributeDefinition$Type("SHORT", _);
        public static const MEMO:TextAttributeDefinition$Type = new TextAttributeDefinition$Type("MEMO", _);

        function TextAttributeDefinition$Type(value:String = null, restrictor:* = null) {
            super((value || SHORT.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [SHORT, MEMO];
        }

        public static function valueOf(name:String):TextAttributeDefinition$Type {
            return TextAttributeDefinition$Type(SHORT.constantOf(name));
        }
    }
}