/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.openforis.collect.remoting.service {
	import mx.collections.ArrayCollection;
	
	import org.openforis.collect.Application;

    [Bindable]
    [RemoteClass(alias="org.openforis.collect.remoting.service.UpdateRequest")]
    public class UpdateRequest extends UpdateRequestBase {
		
		
		public function UpdateRequest(operation:UpdateRequestOperation = null) {
			super();
			autoSave = !Application.preview && Application.autoSave;
			operations = new ArrayCollection();
			if(operation != null) {
				operations.addItem(operation);
			}
		}
		
		public function addOperation(operation:UpdateRequestOperation):void {
			this.operations.addItem(operation);
		}
    }
}