/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (AbstractVersionable.as).
 */

package org.openforis.idm.metamodel.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.openforis.idm.metamodel.ModelVersion;
    import org.openforis.idm.metamodel.Versionable;

    [Bindable]
    public class AbstractVersionableBase implements IExternalizable, Versionable {

        private var _deprecated:ModelVersion;
        private var _since:ModelVersion;

        [Bindable(event="unused")]
        public function get deprecated():ModelVersion {
            return _deprecated;
        }

        [Bindable(event="unused")]
        public function get since():ModelVersion {
            return _since;
        }

        public function readExternal(input:IDataInput):void {
            _deprecated = input.readObject() as ModelVersion;
            _since = input.readObject() as ModelVersion;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_deprecated);
            output.writeObject(_since);
        }
    }
}