/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (AbstractModelObjectDefinition.as).
 */

package org.openforis.idm.metamodel.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.openforis.idm.metamodel.Cardinality;
    import org.openforis.idm.metamodel.EntityDefinition;
    import org.openforis.idm.metamodel.ModelObjectDefinition;

    [Bindable]
    public class AbstractModelObjectDefinitionBase extends AbstractVersionable implements ModelObjectDefinition {

        private var _annotations:ListCollectionView;
        private var _cardinality:Cardinality;
        private var _deprecatedAttribute:String;
        private var _descriptions:ListCollectionView;
        private var _labels:ListCollectionView;
        private var _maxCount:Number;
        private var _minCount:Number;
        private var _multiple:Boolean;
        private var _name:String;
        private var _parentDefinition:EntityDefinition;
        private var _relevantExpression:String;
        private var _requiredExpression:String;
        private var _sinceAttribute:String;

        [Bindable(event="unused")]
        public function get annotations():ListCollectionView {
            return _annotations;
        }

        [Bindable(event="unused")]
        public function get cardinality():Cardinality {
            return _cardinality;
        }

        [Bindable(event="unused")]
        public function get descriptions():ListCollectionView {
            return _descriptions;
        }

        [Bindable(event="unused")]
        public function get labels():ListCollectionView {
            return _labels;
        }

        [Bindable(event="unused")]
        public function get multiple():Boolean {
            return _multiple;
        }

        [Bindable(event="unused")]
        public function get name():String {
            return _name;
        }

        [Bindable(event="unused")]
        public function get parentDefinition():EntityDefinition {
            return _parentDefinition;
        }

        [Bindable(event="unused")]
        public function get relevantExpression():String {
            return _relevantExpression;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _annotations = input.readObject() as ListCollectionView;
            _cardinality = input.readObject() as Cardinality;
            _deprecatedAttribute = input.readObject() as String;
            _descriptions = input.readObject() as ListCollectionView;
            _labels = input.readObject() as ListCollectionView;
            _maxCount = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _minCount = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _multiple = input.readObject() as Boolean;
            _name = input.readObject() as String;
            _parentDefinition = input.readObject() as EntityDefinition;
            _relevantExpression = input.readObject() as String;
            _requiredExpression = input.readObject() as String;
            _sinceAttribute = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_annotations);
            output.writeObject(_cardinality);
            output.writeObject(_deprecatedAttribute);
            output.writeObject(_descriptions);
            output.writeObject(_labels);
            output.writeObject(_maxCount);
            output.writeObject(_minCount);
            output.writeObject(_multiple);
            output.writeObject(_name);
            output.writeObject(_parentDefinition);
            output.writeObject(_relevantExpression);
            output.writeObject(_requiredExpression);
            output.writeObject(_sinceAttribute);
        }

		public function set annotations(value:ListCollectionView):void {
			_annotations = value;
		}

		public function set cardinality(value:Cardinality):void {
			_cardinality = value;
		}

		public function get deprecatedAttribute():String {
			return _deprecatedAttribute;
		}

		public function set deprecatedAttribute(value:String):void {
			_deprecatedAttribute = value;
		}

		public function set descriptions(value:ListCollectionView):void {
			_descriptions = value;
		}

		public function set labels(value:ListCollectionView):void {
			_labels = value;
		}

		public function get maxCount():Number {
			return _maxCount;
		}

		public function set maxCount(value:Number):void {
			_maxCount = value;
		}

		public function get minCount():Number {
			return _minCount;
		}

		public function set minCount(value:Number):void {
			_minCount = value;
		}

		public function set multiple(value:Boolean):void {
			_multiple = value;
		}

		public function set name(value:String):void {
			_name = value;
		}

		public function set parentDefinition(value:EntityDefinition):void {
			_parentDefinition = value;
		}

		public function set relevantExpression(value:String):void {
			_relevantExpression = value;
		}

		public function get requiredExpression():String {
			return _requiredExpression;
		}

		public function set requiredExpression(value:String):void {
			_requiredExpression = value;
		}

		public function get sinceAttribute():String {
			return _sinceAttribute;
		}

		public function set sinceAttribute(value:String):void {
			_sinceAttribute = value;
		}


    }
}