/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (AbstractAttributeDefinition.as).
 */

package org.openforis.idm.metamodel.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.openforis.idm.metamodel.AttributeDefinition;

    [Bindable]
    public class AbstractAttributeDefinitionBase extends AbstractModelObjectDefinition implements AttributeDefinition {

        private var _attributeDefaults:ListCollectionView;
        private var _checks:ListCollectionView;

        [Bindable(event="unused")]
        public function get attributeDefaults():ListCollectionView {
            return _attributeDefaults;
        }

        [Bindable(event="unused")]
        public function get checks():ListCollectionView {
            return _checks;
        }

		public function set checks(value:ListCollectionView):void {
			_checks = value;
		}
		
		public function set attributeDefaults(value:ListCollectionView):void {
			_attributeDefaults = value;
		}

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _attributeDefaults = input.readObject() as ListCollectionView;
            _checks = input.readObject() as ListCollectionView;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_attributeDefaults);
            output.writeObject(_checks);
        }

		

    }
}