/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (CodeDefinitionImpl.as).
 */

package org.openforis.idm.metamodel.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.openforis.idm.metamodel.CodeDefinition;
    import org.openforis.idm.metamodel.CodingScheme;

    [Bindable]
    public class CodeDefinitionImplBase implements IExternalizable, CodeDefinition {

        private var _code:String;
        private var _codingScheme:CodingScheme;
        protected var _schemeName:String;

        [Bindable(event="unused")]
        public function get code():String {
            return _code;
        }

        [Bindable(event="unused")]
        public function get codingScheme():CodingScheme {
            return _codingScheme;
        }

        public function readExternal(input:IDataInput):void {
            _code = input.readObject() as String;
            _codingScheme = input.readObject() as CodingScheme;
            _schemeName = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_code);
            output.writeObject(_codingScheme);
            output.writeObject(_schemeName);
        }
    }
}