/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (ModelVersionImpl.as).
 */

package org.openforis.idm.metamodel.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    
    import mx.collections.ListCollectionView;
    
    import org.openforis.idm.metamodel.ModelVersion;

    [Bindable]
    public class ModelVersionImplBase implements IExternalizable, ModelVersion {

        private var _date:Date;
        private var _descriptions:ListCollectionView;
        private var _labels:ListCollectionView;
        private var _name:String;

        [Bindable(event="unused")]
        public function get date():Date {
            return _date;
        }

        [Bindable(event="unused")]
        public function get descriptions():ListCollectionView {
            return _descriptions;
        }

        [Bindable(event="unused")]
        public function get labels():ListCollectionView {
            return _labels;
        }

        [Bindable(event="unused")]
        public function get name():String {
            return _name;
        }

        public function readExternal(input:IDataInput):void {
            _date = input.readObject() as Date;
            _descriptions = input.readObject() as ListCollectionView;
            _labels = input.readObject() as ListCollectionView;
            _name = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_date);
            output.writeObject(_descriptions);
            output.writeObject(_labels);
            output.writeObject(_name);
        }

		public function set date(value:Date):void {
			_date = value;
		}

		public function set descriptions(value:ListCollectionView):void {
			_descriptions = value;
		}

		public function set labels(value:ListCollectionView):void {
			_labels = value;
		}

		public function set name(value:String):void {
			_name = value;
		}


    }
}