/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (SchemaImpl.as).
 */

package org.openforis.idm.metamodel.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;
    import org.openforis.idm.metamodel.Schema;

    [Bindable]
    public class SchemaImplBase implements IExternalizable, Schema {

        private var _rootEntityDefinitions:ListCollectionView;

        [Bindable(event="unused")]
        public function get rootEntityDefinitions():ListCollectionView {
            return _rootEntityDefinitions;
        }

		public function set rootEntityDefinitions(value:ListCollectionView):void {
			_rootEntityDefinitions = value;
		}
		
        public function readExternal(input:IDataInput):void {
            _rootEntityDefinitions = input.readObject() as ListCollectionView;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_rootEntityDefinitions);
        }
    }
}