/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openforis.collect.idm.model.impl {

    [Bindable]
    [RemoteClass(alias="org.openforis.collect.idm.model.impl.AbstractValue$Symbol")]
    public class AbstractValue$Symbol {

        public static const BLANK_ON_FORM:AbstractValue$Symbol = new AbstractValue$Symbol("BLANK_ON_FORM");
        public static const DASH_ON_FORM:AbstractValue$Symbol = new AbstractValue$Symbol("DASH_ON_FORM");
        public static const ILLEGIBLE:AbstractValue$Symbol = new AbstractValue$Symbol("ILLEGIBLE");

		private var _name:String;
		private var _label:String;
		
        function AbstractValue$Symbol(name:String = null) {
            this._name = name;
        }

        public static function get constants():Array {
            return [BLANK_ON_FORM, DASH_ON_FORM, ILLEGIBLE];
        }

        public static function valueOf(name:String):AbstractValue$Symbol {
			for each(var item:AbstractValue$Symbol in constants) {
				if(item.name == name) {
					return item;
				}
			}
			return null;
        }

		public function get name():String {
			return _name;
		}
		
		public function get label():String {
			return _label;
		}
		
    }
}