/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (CollectAttributeMetadata.as).
 */

package org.openforis.collect.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.openforis.idm.model.AttributeMetadata;

    [Bindable]
    public class CollectAttributeMetadataBase implements IExternalizable, AttributeMetadata {

        private var _remarks:String;
        private var _state:String;
        private var _symbol:String;

        public function set remarks(value:String):void {
            _remarks = value;
        }
        public function get remarks():String {
            return _remarks;
        }

        public function set state(value:String):void {
            _state = value;
        }
        public function get state():String {
            return _state;
        }

        public function set symbol(value:String):void {
            _symbol = value;
        }
        public function get symbol():String {
            return _symbol;
        }

        public function readExternal(input:IDataInput):void {
            _remarks = input.readObject() as String;
            _state = input.readObject() as String;
            _symbol = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_remarks);
            output.writeObject(_state);
            output.writeObject(_symbol);
        }
    }
}