/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (CollectRecord.as).
 */

package org.openforis.collect.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.util.Enum;
    import org.openforis.idm.model.Record;

    [Bindable]
    public class CollectRecordBase extends Record {

        private var _createdBy:String;
        private var _creationDate:Date;
        private var _modifiedBy:String;
        private var _modifiedDate:Date;
        private var _step:CollectRecord$Step;
        private var _submitted:Boolean;

        public function set createdBy(value:String):void {
            _createdBy = value;
        }
        public function get createdBy():String {
            return _createdBy;
        }

        public function set creationDate(value:Date):void {
            _creationDate = value;
        }
        public function get creationDate():Date {
            return _creationDate;
        }

        public function set modifiedBy(value:String):void {
            _modifiedBy = value;
        }
        public function get modifiedBy():String {
            return _modifiedBy;
        }

        public function set modifiedDate(value:Date):void {
            _modifiedDate = value;
        }
        public function get modifiedDate():Date {
            return _modifiedDate;
        }

        public function set step(value:CollectRecord$Step):void {
            _step = value;
        }
        public function get step():CollectRecord$Step {
            return _step;
        }

        public function set submitted(value:Boolean):void {
            _submitted = value;
        }
        public function get submitted():Boolean {
            return _submitted;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _createdBy = input.readObject() as String;
            _creationDate = input.readObject() as Date;
            _modifiedBy = input.readObject() as String;
            _modifiedDate = input.readObject() as Date;
            _step = Enum.readEnum(input) as CollectRecord$Step;
            _submitted = input.readObject() as Boolean;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_createdBy);
            output.writeObject(_creationDate);
            output.writeObject(_modifiedBy);
            output.writeObject(_modifiedDate);
            output.writeObject(_step);
            output.writeObject(_submitted);
        }
    }
}