/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (RecordSummary.as).
 */

package org.openforis.collect.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class RecordSummaryBase implements IExternalizable {

        private var _createdBy:String;
        private var _creationDate:Date;
        private var _errorCount:int;
        private var _id:String;
        private var _modifiedBy:String;
        private var _modifiedDate:Date;
        private var _warningCount:int;

        [Bindable(event="unused")]
        public function get createdBy():String {
            return _createdBy;
        }

        [Bindable(event="unused")]
        public function get creationDate():Date {
            return _creationDate;
        }

        [Bindable(event="unused")]
        public function get errorCount():int {
            return _errorCount;
        }

        [Bindable(event="unused")]
        public function get id():String {
            return _id;
        }

        [Bindable(event="unused")]
        public function get modifiedBy():String {
            return _modifiedBy;
        }

        [Bindable(event="unused")]
        public function get modifiedDate():Date {
            return _modifiedDate;
        }

        [Bindable(event="unused")]
        public function get warningCount():int {
            return _warningCount;
        }

        public function readExternal(input:IDataInput):void {
            _createdBy = input.readObject() as String;
            _creationDate = input.readObject() as Date;
            _errorCount = input.readObject() as int;
            _id = input.readObject() as String;
            _modifiedBy = input.readObject() as String;
            _modifiedDate = input.readObject() as Date;
            _warningCount = input.readObject() as int;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_createdBy);
            output.writeObject(_creationDate);
            output.writeObject(_errorCount);
            output.writeObject(_id);
            output.writeObject(_modifiedBy);
            output.writeObject(_modifiedDate);
            output.writeObject(_warningCount);
        }
    }
}