/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (SessionState.as).
 */

package org.openforis.collect.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.openforis.idm.model.Record;

    [Bindable]
    public class SessionStateBase implements IExternalizable {

        private var _activeRecord:Record;
        private var _sessionId:String;
        private var _user:User;

        public function set activeRecord(value:Record):void {
            _activeRecord = value;
        }
        public function get activeRecord():Record {
            return _activeRecord;
        }

        public function set sessionId(value:String):void {
            _sessionId = value;
        }
        public function get sessionId():String {
            return _sessionId;
        }

        public function set user(value:User):void {
            _user = value;
        }
        public function get user():User {
            return _user;
        }

        public function readExternal(input:IDataInput):void {
            _activeRecord = input.readObject() as Record;
            _sessionId = input.readObject() as String;
            _user = input.readObject() as User;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_activeRecord);
            output.writeObject(_sessionId);
            output.writeObject(_user);
        }
    }
}