/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (BooleanAttributeDefinition.as).
 */

package org.openforis.idm.metamodel {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class BooleanAttributeDefinitionBase extends AttributeDefinition {

        private var _affirmativeOnly:Boolean;

        [Bindable(event="unused")]
        public function get affirmativeOnly():Boolean {
            return _affirmativeOnly;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _affirmativeOnly = input.readObject() as Boolean;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_affirmativeOnly);
        }
    }
}