/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openforis.idm.metamodel {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.openforis.idm.metamodel.Check$Flag")]
    public class Check$Flag extends Enum {

        public static const ERROR:Check$Flag = new Check$Flag("ERROR", _);
        public static const WARN:Check$Flag = new Check$Flag("WARN", _);

        function Check$Flag(value:String = null, restrictor:* = null) {
            super((value || ERROR.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [ERROR, WARN];
        }

        public static function valueOf(name:String):Check$Flag {
            return Check$Flag(ERROR.constantOf(name));
        }
    }
}