/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openforis.idm.metamodel {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.openforis.idm.metamodel.CodeAttributeDefinition$Type")]
    public class CodeAttributeDefinition$Type extends Enum {

        public static const ITEM:CodeAttributeDefinition$Type = new CodeAttributeDefinition$Type("ITEM", _);
        public static const LIST:CodeAttributeDefinition$Type = new CodeAttributeDefinition$Type("LIST", _);

        function CodeAttributeDefinition$Type(value:String = null, restrictor:* = null) {
            super((value || ITEM.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [ITEM, LIST];
        }

        public static function valueOf(name:String):CodeAttributeDefinition$Type {
            return CodeAttributeDefinition$Type(ITEM.constantOf(name));
        }
    }
}