/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openforis.idm.metamodel {

    public interface CodeAttributeDefinition extends AttributeDefinition {

        function get allowUnlisted():Boolean;

        function get key():Boolean;

        function get list():CodeList;

        function get parentExpression():String;
    }
}