/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openforis.idm.metamodel {

    import mx.collections.ListCollectionView;

    public interface CodeList extends Versionable {

        function get codingSchemes():ListCollectionView;

        function get descriptions():ListCollectionView;

        function get hierarchy():ListCollectionView;

        function get items():ListCollectionView;

        function get labels():ListCollectionView;

        function get name():String;
    }
}