/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openforis.idm.metamodel {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.openforis.idm.metamodel.CodingScheme$CodeScope")]
    public class CodingScheme$CodeScope extends Enum {

        public static const SCHEME:CodingScheme$CodeScope = new CodingScheme$CodeScope("SCHEME", _);
        public static const LOCAL:CodingScheme$CodeScope = new CodingScheme$CodeScope("LOCAL", _);

        function CodingScheme$CodeScope(value:String = null, restrictor:* = null) {
            super((value || SCHEME.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [SCHEME, LOCAL];
        }

        public static function valueOf(name:String):CodingScheme$CodeScope {
            return CodingScheme$CodeScope(SCHEME.constantOf(name));
        }
    }
}