/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (CodingScheme.as).
 */

package org.openforis.idm.metamodel {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.granite.util.Enum;

    [Bindable]
    public class CodingSchemeBase implements IExternalizable {

        private var _codeScope:CodeList$CodeScope;
        private var _codeType:CodeList$CodeType;

        [Bindable(event="unused")]
        public function get codeScope():CodeList$CodeScope {
            return _codeScope;
        }

        [Bindable(event="unused")]
        public function get codeType():CodeList$CodeType {
            return _codeType;
        }

        public function readExternal(input:IDataInput):void {
            _codeScope = Enum.readEnum(input) as CodeList$CodeScope;
            _codeType = Enum.readEnum(input) as CodeList$CodeType;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_codeScope);
            output.writeObject(_codeType);
        }
    }
}