/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openforis.idm.metamodel {

    public interface DistanceCheck extends Check {

        function get destinationPointExpression():String;

        function get maxDistanceExpression():String;

        function get minDistanceExpression():String;

        function get sourcePointExpression():String;
    }
}