/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (EntityDefinition.as).
 */

package org.openforis.idm.metamodel {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class EntityDefinitionBase extends NodeDefinition {

        private var _childDefinitions:ListCollectionView;

        [Bindable(event="unused")]
        public function get childDefinitions():ListCollectionView {
            return _childDefinitions;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _childDefinitions = input.readObject() as ListCollectionView;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_childDefinitions);
        }
    }
}