/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (FileAttributeDefinition.as).
 */

package org.openforis.idm.metamodel {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class FileAttributeDefinitionBase extends AttributeDefinition {

        private var _extensions:ListCollectionView;
        private var _maxSize:Number;

        [Bindable(event="unused")]
        public function get extensions():ListCollectionView {
            return _extensions;
        }

        [Bindable(event="unused")]
        public function get maxSize():Number {
            return _maxSize;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _extensions = input.readObject() as ListCollectionView;
            _maxSize = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_extensions);
            output.writeObject(_maxSize);
        }
    }
}