/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openforis.idm.metamodel {

    [Bindable]
    [RemoteClass(alias="org.openforis.idm.metamodel.ModelObjectLabel$LabelType")]
    public class ModelObjectLabel$LabelType {

        public static const INSTANCE:ModelObjectLabel$LabelType = new ModelObjectLabel$LabelType("INSTANCE");
        public static const LIST:ModelObjectLabel$LabelType = new ModelObjectLabel$LabelType("LIST");
        public static const PROMPT:ModelObjectLabel$LabelType = new ModelObjectLabel$LabelType("PROMPT");
        public static const NUMBER:ModelObjectLabel$LabelType = new ModelObjectLabel$LabelType("NUMBER");

		private var _name:String;
		
        function ModelObjectLabel$LabelType(value:String = null) {
			this.name = name;
        }

       	public static function get constants():Array {
            return [INSTANCE, LIST, PROMPT, NUMBER];
        }

		public static function valueOf(name:String):ModelObjectLabel$LabelType {
			for each(var item:ModelObjectLabel$LabelType in constants) {
				if(item.name == name) {
					return item;
				}
			}
			return null;
		}
		public function get name():String {
			return _name;
		}

		public function set name(value:String):void {
			_name = value;
		}

    }
}