/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.openforis.idm.metamodel {

    import mx.collections.ListCollectionView;

    [Bindable]
    [RemoteClass(alias="org.openforis.idm.metamodel.NodeDefinition")]
    public class NodeDefinition extends NodeDefinitionBase {

        override public function get annotationNames():ListCollectionView {
            // TODO: Gas3 default generated getter.
            return null;
        }
    }
}