/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openforis.idm.metamodel {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.openforis.idm.metamodel.NumericAttributeDefinition$Type")]
    public class NumericAttributeDefinition$Type extends Enum {

        public static const INTEGER:NumericAttributeDefinition$Type = new NumericAttributeDefinition$Type("INTEGER", _);
        public static const REAL:NumericAttributeDefinition$Type = new NumericAttributeDefinition$Type("REAL", _);

        function NumericAttributeDefinition$Type(value:String = null, restrictor:* = null) {
            super((value || INTEGER.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [INTEGER, REAL];
        }

        public static function valueOf(name:String):NumericAttributeDefinition$Type {
            return NumericAttributeDefinition$Type(INTEGER.constantOf(name));
        }
    }
}