/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (NumericAttributeDefinition.as).
 */

package org.openforis.idm.metamodel {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.granite.util.Enum;

    [Bindable]
    public class NumericAttributeDefinitionBase extends AttributeDefinition {

        private var _precisionDefinitions:ListCollectionView;
        private var _type:NumericAttributeDefinition$Type;

        [Bindable(event="unused")]
        public function get precisionDefinitions():ListCollectionView {
            return _precisionDefinitions;
        }

        [Bindable(event="unused")]
        public function get type():NumericAttributeDefinition$Type {
            return _type;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _precisionDefinitions = input.readObject() as ListCollectionView;
            _type = Enum.readEnum(input) as NumericAttributeDefinition$Type;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_precisionDefinitions);
            output.writeObject(_type);
        }
    }
}