/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (PatternCheck.as).
 */

package org.openforis.idm.metamodel {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class PatternCheckBase extends Check {

        private var _regularExpression:String;

        [Bindable(event="unused")]
        public function get regularExpression():String {
            return _regularExpression;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _regularExpression = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_regularExpression);
        }
    }
}