/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Precision.as).
 */

package org.openforis.idm.metamodel {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class PrecisionBase implements IExternalizable {

        private var _decimalDigits:Number;
        private var _defaultPrecision:Boolean;
        private var _definition:NumericAttributeDefinition;
        private var _unit:Unit;

        [Bindable(event="unused")]
        public function get decimalDigits():Number {
            return _decimalDigits;
        }

        [Bindable(event="unused")]
        public function get defaultPrecision():Boolean {
            return _defaultPrecision;
        }

        [Bindable(event="unused")]
        public function get definition():NumericAttributeDefinition {
            return _definition;
        }

        [Bindable(event="unused")]
        public function get unit():Unit {
            return _unit;
        }

        public function readExternal(input:IDataInput):void {
            _decimalDigits = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _defaultPrecision = input.readObject() as Boolean;
            _definition = input.readObject() as NumericAttributeDefinition;
            _unit = input.readObject() as Unit;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_decimalDigits);
            output.writeObject(_defaultPrecision);
            output.writeObject(_definition);
            output.writeObject(_unit);
        }
    }
}