/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Schema.as).
 */

package org.openforis.idm.metamodel {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;
    import org.granite.collections.IMap;

    [Bindable]
    public class SchemaBase implements IExternalizable {

        private var _definitionsById:IMap;
        private var _definitionsByPath:IMap;
        private var _rootEntityDefinitions:ListCollectionView;
        private var _survey:Survey;

        [Bindable(event="unused")]
        public function get rootEntityDefinitions():ListCollectionView {
            return _rootEntityDefinitions;
        }

        [Bindable(event="unused")]
        public function get survey():Survey {
            return _survey;
        }

        public function readExternal(input:IDataInput):void {
            _definitionsById = input.readObject() as IMap;
            _definitionsByPath = input.readObject() as IMap;
            _rootEntityDefinitions = input.readObject() as ListCollectionView;
            _survey = input.readObject() as Survey;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_definitionsById);
            output.writeObject(_definitionsByPath);
            output.writeObject(_rootEntityDefinitions);
            output.writeObject(_survey);
        }
    }
}