/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openforis.idm.metamodel {

    import mx.collections.ListCollectionView;

    public interface Unit {

        function get abbreviations():ListCollectionView;

        function get conversionFactor():Number;

        function get dimension():String;

        function get labels():ListCollectionView;

        function get name():String;
    }
}