/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Versionable.as).
 */

package org.openforis.idm.metamodel {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class VersionableBase implements IExternalizable {

        private var _deprecatedVersion:ModelVersion;
        private var _sinceVersion:ModelVersion;

        [Bindable(event="unused")]
        public function get deprecatedVersion():ModelVersion {
            return _deprecatedVersion;
        }

        [Bindable(event="unused")]
        public function get sinceVersion():ModelVersion {
            return _sinceVersion;
        }

        public function readExternal(input:IDataInput):void {
            _deprecatedVersion = input.readObject() as ModelVersion;
            _sinceVersion = input.readObject() as ModelVersion;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_deprecatedVersion);
            output.writeObject(_sinceVersion);
        }
    }
}