/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (AbstractNumericAttributeDefinition.as).
 */

package org.openforis.idm.metamodel.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.granite.util.Enum;
    import org.openforis.idm.metamodel.NumberAttributeDefinition;
    import org.openforis.idm.metamodel.NumericAttributeDefinition$Type;

    [Bindable]
    public class AbstractNumericAttributeDefinitionBase extends AbstractAttributeDefinition implements NumberAttributeDefinition {

        private var _precisionDefinitions:ListCollectionView;
        private var _type:NumericAttributeDefinition$Type;

        [Bindable(event="unused")]
        public function get precisionDefinitions():ListCollectionView {
            return _precisionDefinitions;
        }

        [Bindable(event="unused")]
        public function get type():NumericAttributeDefinition$Type {
            return _type;
        }
		
		public function set precisionDefinitions(value:ListCollectionView):void {
			_precisionDefinitions = value;
		}
		
		public function set type(value:NumericAttributeDefinition$Type):void {
			_type = value;
		}
		
        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _precisionDefinitions = input.readObject() as ListCollectionView;
            _type = Enum.readEnum(input) as NumericAttributeDefinition$Type;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_precisionDefinitions);
            output.writeObject(_type);
        }

		
    }
}