/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (AttributeDefaultImpl.as).
 */

package org.openforis.idm.metamodel.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.openforis.idm.metamodel.AttributeDefault;

    [Bindable]
    public class AttributeDefaultImplBase implements IExternalizable, AttributeDefault {

        private var _condition:String;
        private var _expression:String;

        [Bindable(event="unused")]
        public function get condition():String {
            return _condition;
        }

        [Bindable(event="unused")]
        public function get expression():String {
            return _expression;
        }

        public function readExternal(input:IDataInput):void {
            _condition = input.readObject() as String;
            _expression = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_condition);
            output.writeObject(_expression);
        }
    }
}