/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (CardinalityImpl.as).
 */

package org.openforis.idm.metamodel.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.openforis.idm.metamodel.Cardinality;

    [Bindable]
    public class CardinalityImplBase implements IExternalizable, Cardinality {

        private var _maxCount:Number;
        private var _minCount:Number;
        private var _requiredExpression:String;

        [Bindable(event="unused")]
        public function get maxCount():Number {
            return _maxCount;
        }

        [Bindable(event="unused")]
        public function get minCount():Number {
            return _minCount;
        }

        [Bindable(event="unused")]
        public function get requiredExpression():String {
            return _requiredExpression;
        }

        public function readExternal(input:IDataInput):void {
            _maxCount = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _minCount = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _requiredExpression = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_maxCount);
            output.writeObject(_minCount);
            output.writeObject(_requiredExpression);
        }
    }
}