/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (CodeListImpl.as).
 */

package org.openforis.idm.metamodel.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.openforis.idm.metamodel.CodeList;

    [Bindable]
    public class CodeListImplBase extends AbstractVersionable implements CodeList {

        private var _codingSchemes:ListCollectionView;
        protected var _deprecatedAttribute:String;
        private var _descriptions:ListCollectionView;
        private var _hierarchy:ListCollectionView;
        private var _items:ListCollectionView;
        private var _labels:ListCollectionView;
        private var _name:String;
        protected var _sinceAttribute:String;

        [Bindable(event="unused")]
        public function get codingSchemes():ListCollectionView {
            return _codingSchemes;
        }

        [Bindable(event="unused")]
        public function get descriptions():ListCollectionView {
            return _descriptions;
        }

        [Bindable(event="unused")]
        public function get hierarchy():ListCollectionView {
            return _hierarchy;
        }

        [Bindable(event="unused")]
        public function get items():ListCollectionView {
            return _items;
        }

        [Bindable(event="unused")]
        public function get labels():ListCollectionView {
            return _labels;
        }

        [Bindable(event="unused")]
        public function get name():String {
            return _name;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _codingSchemes = input.readObject() as ListCollectionView;
            _deprecatedAttribute = input.readObject() as String;
            _descriptions = input.readObject() as ListCollectionView;
            _hierarchy = input.readObject() as ListCollectionView;
            _items = input.readObject() as ListCollectionView;
            _labels = input.readObject() as ListCollectionView;
            _name = input.readObject() as String;
            _sinceAttribute = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_codingSchemes);
            output.writeObject(_deprecatedAttribute);
            output.writeObject(_descriptions);
            output.writeObject(_hierarchy);
            output.writeObject(_items);
            output.writeObject(_labels);
            output.writeObject(_name);
            output.writeObject(_sinceAttribute);
        }
    }
}