/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.openforis.idm.metamodel.impl {

    [Bindable]
    [RemoteClass(alias="org.openforis.idm.metamodel.impl.CodeListLevelImpl")]
    public class CodeListLevelImpl extends CodeListLevelImplBase {
    }
}