/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (EntityDefinitionImpl.as).
 */

package org.openforis.idm.metamodel.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;
    import org.openforis.idm.metamodel.EntityDefinition;

    [Bindable]
    public class EntityDefinitionImplBase extends AbstractModelObjectDefinition implements EntityDefinition {

        private var _childDefinitions:ListCollectionView;

        [Bindable(event="unused")]
        public function get childDefinitions():ListCollectionView {
            return _childDefinitions;
        }
		public function set childDefinitions(value:ListCollectionView):void {
			_childDefinitions = value;
		}
		
        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _childDefinitions = input.readObject() as ListCollectionView;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_childDefinitions);
        }
    }
}