/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (MetaModelUnmarshallerListener.as).
 */

package org.openforis.idm.metamodel.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.openforis.idm.metamodel.CodeList;
    import org.openforis.idm.metamodel.Survey;

    [Bindable]
    public class MetaModelUnmarshallerListenerBase implements IExternalizable {

        protected var _currentCodeList:CodeList;
        protected var _survey:Survey;

        public function readExternal(input:IDataInput):void {
            _currentCodeList = input.readObject() as CodeList;
            _survey = input.readObject() as Survey;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_currentCodeList);
            output.writeObject(_survey);
        }
    }
}