/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (ModelImpl.as).
 */

package org.openforis.idm.metamodel.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;
    import org.openforis.idm.metamodel.Schema;

    [Bindable]
    public class ModelImplBase implements IExternalizable {

        private var _codeLists:ListCollectionView;
        private var _schema:Schema;
        private var _units:ListCollectionView;
        private var _versions:ListCollectionView;

        public function set codeLists(value:ListCollectionView):void {
            _codeLists = value;
        }
        public function get codeLists():ListCollectionView {
            return _codeLists;
        }

        public function set schema(value:Schema):void {
            _schema = value;
        }
        public function get schema():Schema {
            return _schema;
        }

        public function set units(value:ListCollectionView):void {
            _units = value;
        }
        public function get units():ListCollectionView {
            return _units;
        }

        public function set versions(value:ListCollectionView):void {
            _versions = value;
        }
        public function get versions():ListCollectionView {
            return _versions;
        }

        public function readExternal(input:IDataInput):void {
            _codeLists = input.readObject() as ListCollectionView;
            _schema = input.readObject() as Schema;
            _units = input.readObject() as ListCollectionView;
            _versions = input.readObject() as ListCollectionView;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_codeLists);
            output.writeObject(_schema);
            output.writeObject(_units);
            output.writeObject(_versions);
        }
    }
}