/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (ModelObjectLabelImpl.as).
 */

package org.openforis.idm.metamodel.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.openforis.idm.metamodel.ModelObjectLabel;
    import org.openforis.idm.metamodel.ModelObjectLabel$LabelType;

    [Bindable]
    public class ModelObjectLabelImplBase extends LanguageSpecificTextImpl implements ModelObjectLabel {

        private var _labelType:ModelObjectLabel$LabelType;

        [Bindable(event="unused")]
        public function get labelType():ModelObjectLabel$LabelType {
            return _labelType;
        }

		public function set labelType(value:ModelObjectLabel$LabelType):void {
			_labelType = value;
		}

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            //_labelType = Enum.readEnum(input) as ModelObjectLabel$LabelType;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_labelType);
        }

		
    }
}