/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (PatternCheckImpl.as).
 */

package org.openforis.idm.metamodel.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import java.util.regex.Pattern;
    import org.openforis.idm.metamodel.PatternCheck;

    [Bindable]
    public class PatternCheckImplBase extends AbstractCheck implements PatternCheck {

        private var _pattern:Pattern;
        private var _regularExpression:String;

        [Bindable(event="unused")]
        public function get regularExpression():String {
            return _regularExpression;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _pattern = input.readObject() as Pattern;
            _regularExpression = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_pattern);
            output.writeObject(_regularExpression);
        }
    }
}