/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (PrecisionImpl.as).
 */

package org.openforis.idm.metamodel.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.openforis.idm.metamodel.Precision;
    import org.openforis.idm.metamodel.Unit;

    [Bindable]
    public class PrecisionImplBase implements IExternalizable, Precision {

        private var _decimalDigits:Number;
        private var _defaultPrecision:Boolean;
        private var _unit:Unit;
        protected var _unitAttribute:String;

        [Bindable(event="unused")]
        public function get decimalDigits():Number {
            return _decimalDigits;
        }

        [Bindable(event="unused")]
        public function get defaultPrecision():Boolean {
            return _defaultPrecision;
        }

        [Bindable(event="unused")]
        public function get unit():Unit {
            return _unit;
        }

        public function readExternal(input:IDataInput):void {
            _decimalDigits = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _defaultPrecision = input.readObject() as Boolean;
            _unit = input.readObject() as Unit;
            _unitAttribute = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_decimalDigits);
            output.writeObject(_defaultPrecision);
            output.writeObject(_unit);
            output.writeObject(_unitAttribute);
        }
    }
}