/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (SurveyImpl.as).
 */

package org.openforis.idm.metamodel.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    
    import mx.collections.ListCollectionView;
    
    import org.openforis.idm.metamodel.Schema;
    import org.openforis.idm.metamodel.Survey;

    [Bindable]
    public class SurveyImplBase implements IExternalizable, Survey {

        private var _codeLists:ListCollectionView;
        private var _configuration:XML;
        private var _cycle:Number;
        private var _descriptions:ListCollectionView;
        private var _name:String;
        private var _projectNames:ListCollectionView;
        private var _schema:Schema;
        private var _spatialReferenceSystems:ListCollectionView;
        private var _units:ListCollectionView;
        private var _versions:ListCollectionView;

        [Bindable(event="unused")]
        public function get codeLists():ListCollectionView {
            return _codeLists;
        }

        [Bindable(event="unused")]
        public function get configuration():XML {
            return _configuration;
        }

        [Bindable(event="unused")]
        public function get cycle():Number {
            return _cycle;
        }

        [Bindable(event="unused")]
        public function get descriptions():ListCollectionView {
            return _descriptions;
        }

        [Bindable(event="unused")]
        public function get name():String {
            return _name;
        }

        [Bindable(event="unused")]
        public function get projectNames():ListCollectionView {
            return _projectNames;
        }

        [Bindable(event="unused")]
        public function get schema():Schema {
            return _schema;
        }

        [Bindable(event="unused")]
        public function get spatialReferenceSystems():ListCollectionView {
            return _spatialReferenceSystems;
        }

        [Bindable(event="unused")]
        public function get units():ListCollectionView {
            return _units;
        }

        [Bindable(event="unused")]
        public function get versions():ListCollectionView {
            return _versions;
        }

        public function readExternal(input:IDataInput):void {
            _codeLists = input.readObject() as ListCollectionView;
            _configuration = input.readObject() as XML;
            _cycle = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _descriptions = input.readObject() as ListCollectionView;
            _name = input.readObject() as String;
            _projectNames = input.readObject() as ListCollectionView;
            _schema = input.readObject() as Schema;
            _spatialReferenceSystems = input.readObject() as ListCollectionView;
            _units = input.readObject() as ListCollectionView;
            _versions = input.readObject() as ListCollectionView;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_codeLists);
            output.writeObject(_configuration);
            output.writeObject(_cycle);
            output.writeObject(_descriptions);
            output.writeObject(_name);
            output.writeObject(_projectNames);
            output.writeObject(_schema);
            output.writeObject(_spatialReferenceSystems);
            output.writeObject(_units);
            output.writeObject(_versions);
        }

		public function set schema(value:Schema):void {
			_schema = value;
		}

		public function set codeLists(value:ListCollectionView):void {
			_codeLists = value;
		}

		public function set cycle(value:Number):void {
			_cycle = value;
		}

		public function set descriptions(value:ListCollectionView):void {
			_descriptions = value;
		}

		public function set name(value:String):void {
			_name = value;
		}

		public function set projectNames(value:ListCollectionView):void {
			_projectNames = value;
		}

		public function set spatialReferenceSystems(value:ListCollectionView):void {
			_spatialReferenceSystems = value;
		}

		public function set units(value:ListCollectionView):void {
			_units = value;
		}

		public function set versions(value:ListCollectionView):void {
			_versions = value;
		}

		public function set configuration(value:XML):void {
			_configuration = value;
		}

		
    }
}