/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (TimeAttributeDefinitionImpl.as).
 */

package org.openforis.idm.metamodel.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.openforis.idm.metamodel.TimeAttributeDefinition;

    [Bindable]
    public class TimeAttributeDefinitionImplBase extends AbstractTimestampAttributeDefinition implements TimeAttributeDefinition {


        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
        }
    }
}