/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.openforis.idm.metamodel.jxpath {

    [Bindable]
    [RemoteClass(alias="org.openforis.idm.metamodel.jxpath.NodeDefinitionDynamicPropertyHandler")]
    public class NodeDefinitionDynamicPropertyHandler extends NodeDefinitionDynamicPropertyHandlerBase {
    }
}