/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.openforis.idm.model.jxpath {

    [Bindable]
    [RemoteClass(alias="org.openforis.idm.model.jxpath.RecordPropertyHandler")]
    public class RecordPropertyHandler extends RecordPropertyHandlerBase {
    }
}