/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (AttributeImpl.as).
 */

package org.openforis.collect.idm.model.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    [Bindable]
    public class AttributeImplBase extends AbstractModelObject {

        private var _value:AbstractValue;
		
        public function set value(value:AbstractValue):void {
            _value = value;
        }
        public function get value():AbstractValue {
            return _value;
        }
		override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _value = input.readObject() as Value;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_value);
        }
    }
}