/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.openforis.collect.idm.model.impl {

    [Bindable]
    [RemoteClass(alias="org.openforis.collect.idm.model.impl.RecordImpl")]
    public class RecordImpl extends RecordImplBase {
    }
}