/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (RecordImpl.as).
 */

package org.openforis.collect.idm.model.impl {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.openforis.idm.metamodel.ModelVersion;
    import org.openforis.idm.metamodel.Survey;
    import org.openforis.idm.model.Entity;

    [Bindable]
    public class RecordImplBase implements IExternalizable {

        private var _createdBy:String;
        private var _creationDate:Date;
        private var _id:Number;
        private var _listener:ModelObjectListener;
        private var _modifiedBy:String;
        private var _modifiedDate:Date;
        private var _rootEntity:Entity;
        private var _survey:Survey;
        private var _version:ModelVersion;

        public function set createdBy(value:String):void {
            _createdBy = value;
        }
        public function get createdBy():String {
            return _createdBy;
        }

        public function set creationDate(value:Date):void {
            _creationDate = value;
        }
        public function get creationDate():Date {
            return _creationDate;
        }

        public function set id(value:Number):void {
            _id = value;
        }
        public function get id():Number {
            return _id;
        }

        public function set modifiedBy(value:String):void {
            _modifiedBy = value;
        }
        public function get modifiedBy():String {
            return _modifiedBy;
        }

        public function set modifiedDate(value:Date):void {
            _modifiedDate = value;
        }
        public function get modifiedDate():Date {
            return _modifiedDate;
        }

        public function set rootEntity(value:Entity):void {
            _rootEntity = value;
        }
        public function get rootEntity():Entity {
            return _rootEntity;
        }

        [Bindable(event="unused")]
        public function get survey():Survey {
            return _survey;
        }

        public function set version(value:ModelVersion):void {
            _version = value;
        }
        public function get version():ModelVersion {
            return _version;
        }

        public function readExternal(input:IDataInput):void {
            _createdBy = input.readObject() as String;
            _creationDate = input.readObject() as Date;
            _id = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _listener = input.readObject() as ModelObjectListener;
            _modifiedBy = input.readObject() as String;
            _modifiedDate = input.readObject() as Date;
            _rootEntity = input.readObject() as Entity;
            _survey = input.readObject() as Survey;
            _version = input.readObject() as ModelVersion;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_createdBy);
            output.writeObject(_creationDate);
            output.writeObject(_id);
            output.writeObject(_listener);
            output.writeObject(_modifiedBy);
            output.writeObject(_modifiedDate);
            output.writeObject(_rootEntity);
            output.writeObject(_survey);
            output.writeObject(_version);
        }
    }
}