/*
Script generated by Aqua Data Studio 10.0.4 on Jan-13-2012 05:22:01 PM
Database: null
Schema: <All Schemas>
*/

ALTER TABLE "collect"."data"
	DROP CONSTRAINT "FK_data_parent" CASCADE 
GO
ALTER TABLE "collect"."data"
	DROP CONSTRAINT "FK_data_record" CASCADE 
GO
ALTER TABLE "collect"."data"
	DROP CONSTRAINT "FK_data_schema_definition" CASCADE 
GO
ALTER TABLE "collect"."record"
	DROP CONSTRAINT "FK_record_root_entity" CASCADE 
GO
ALTER TABLE "collect"."schema_definition"
	DROP CONSTRAINT "FK_schema_definition_survey" CASCADE 
GO
ALTER TABLE "collect"."taxon_name"
	DROP CONSTRAINT "FK_taxon_name_taxon" CASCADE 
GO
ALTER TABLE "collect"."data"
	DROP CONSTRAINT "FK_data_taxon" CASCADE 
GO
ALTER TABLE "collect"."taxon"
	DROP CONSTRAINT "FK_taxon_taxonomy" CASCADE 
GO
ALTER TABLE "collect"."user_role"
	DROP CONSTRAINT "FK_user_user_role" CASCADE 
GO
ALTER TABLE "collect"."record"
	DROP CONSTRAINT "FK_record_locked_by_user" CASCADE 
GO
ALTER TABLE "collect"."record"
	DROP CONSTRAINT "FK_record_created_by_user" CASCADE 
GO
ALTER TABLE "collect"."record"
	DROP CONSTRAINT "FK_record_modified_by_user" CASCADE 
GO
ALTER TABLE "collect"."survey"
	DROP CONSTRAINT "UK_survey_name" CASCADE 
GO
ALTER TABLE "collect"."survey"
	DROP CONSTRAINT "UK_survey_uri" CASCADE 
GO
DROP TABLE "collect"."data"
GO
DROP TABLE "collect"."record"
GO
DROP TABLE "collect"."schema_definition"
GO
DROP TABLE "collect"."survey"
GO
DROP TABLE "collect"."taxon"
GO
DROP TABLE "collect"."taxon_name"
GO
DROP TABLE "collect"."taxonomy"
GO
DROP TABLE "collect"."user"
GO
DROP TABLE "collect"."user_role"
GO
CREATE TABLE "collect"."data"  ( 
	"id"           	integer NOT NULL,
	"record_id"    	integer NOT NULL,
	"definition_id"	integer NOT NULL,
	"number1"      	float NULL,
	"number2"      	float NULL,
	"number3"      	float NULL,
	"text1"        	varchar(2048) NULL,
	"text2"        	varchar(2048) NULL,
	"text3"        	varchar(2048) NULL,
	"taxon_id"     	integer NULL,
	"remarks"      	varchar(2048) NULL,
	"symbol"       	char(1) NULL,
	"state"        	char(1) NULL,
	"parent_id"    	integer NULL,
	"idx"          	integer NOT NULL,
	PRIMARY KEY("id")
)
GO
CREATE TABLE "collect"."record"  ( 
	"id"            	integer NOT NULL,
	"root_entity_id"	integer NOT NULL,
	"date_created"  	timestamp NULL,
	"created_by_id" 	integer NULL,
	"date_modified" 	timestamp NULL,
	"modified_by_id"	integer NULL,
	"model_version" 	varchar(255) NOT NULL,
	"step"          	integer NULL,
	"state"         	char(1) NULL,
	"locked_by_id"  	integer NULL,
	PRIMARY KEY("id")
)
GO
CREATE TABLE "collect"."schema_definition"  ( 
	"id"       	integer NOT NULL,
	"survey_id"	integer NOT NULL,
	"path"     	varchar(255) NOT NULL,
	PRIMARY KEY("id")
)
GO
CREATE TABLE "collect"."survey"  ( 
	"id"  	integer NOT NULL,
	"name"	varchar(255) NOT NULL,
	"uri" 	varchar(255) NULL,
	"idml"	text NOT NULL,
	PRIMARY KEY("id")
)
GO
CREATE TABLE "collect"."taxon"  ( 
	"id"             	integer NOT NULL,
	"scientific_name"	varchar(255) NOT NULL,
	"level"          	integer NOT NULL,
	"taxonomy_id"    	integer NOT NULL,
	"step"           	integer NOT NULL,
	PRIMARY KEY("id")
)
GO
CREATE TABLE "collect"."taxon_name"  ( 
	"id"              	integer NOT NULL,
	"name"            	varchar(255) NULL,
	"language_code"   	char(3) NOT NULL,
	"language_variety"	varchar(255) NULL,
	"taxon_id"        	integer NULL,
	"step"            	integer NOT NULL,
	PRIMARY KEY("id")
)
GO
COMMENT ON COLUMN "collect"."taxon_name"."language_variety" IS 'Dialect, lect, sublanguage or other'
GO
CREATE TABLE "collect"."taxonomy"  ( 
	"id"      	integer NOT NULL,
	"key"     	varchar(255) NOT NULL,
	"metadata"	text NOT NULL,
	PRIMARY KEY("id")
)
GO
CREATE TABLE "collect"."user"  ( 
	"id"      	integer NOT NULL,
	"username"	varchar(255) NOT NULL,
	"password"	varchar(255) NOT NULL,
	"enabled" 	char(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY("id")
)
GO
CREATE TABLE "collect"."user_role"  ( 
	"id"     	integer NOT NULL,
	"user_id"	integer NOT NULL,
	"role"   	varchar(256) NULL,
	PRIMARY KEY("id")
)
GO
ALTER TABLE "collect"."survey"
	ADD CONSTRAINT "UK_survey_name"
	UNIQUE ("name")
GO
ALTER TABLE "collect"."survey"
	ADD CONSTRAINT "UK_survey_uri"
	UNIQUE ("uri")
GO
ALTER TABLE "collect"."data"
	ADD CONSTRAINT "FK_data_parent"
	FOREIGN KEY("parent_id")
	REFERENCES "collect"."data"("id")
GO
ALTER TABLE "collect"."data"
	ADD CONSTRAINT "FK_data_record"
	FOREIGN KEY("record_id")
	REFERENCES "collect"."record"("id")
GO
ALTER TABLE "collect"."data"
	ADD CONSTRAINT "FK_data_schema_definition"
	FOREIGN KEY("definition_id")
	REFERENCES "collect"."schema_definition"("id")
GO
ALTER TABLE "collect"."record"
	ADD CONSTRAINT "FK_record_root_entity"
	FOREIGN KEY("root_entity_id")
	REFERENCES "collect"."schema_definition"("id")
GO
ALTER TABLE "collect"."schema_definition"
	ADD CONSTRAINT "FK_schema_definition_survey"
	FOREIGN KEY("survey_id")
	REFERENCES "collect"."survey"("id")
GO
ALTER TABLE "collect"."taxon_name"
	ADD CONSTRAINT "FK_taxon_name_taxon"
	FOREIGN KEY("taxon_id")
	REFERENCES "collect"."taxon"("id")
GO
ALTER TABLE "collect"."data"
	ADD CONSTRAINT "FK_data_taxon"
	FOREIGN KEY("taxon_id")
	REFERENCES "collect"."taxon"("id")
GO
ALTER TABLE "collect"."taxon"
	ADD CONSTRAINT "FK_taxon_taxonomy"
	FOREIGN KEY("taxonomy_id")
	REFERENCES "collect"."taxonomy"("id")
GO
ALTER TABLE "collect"."user_role"
	ADD CONSTRAINT "FK_user_user_role"
	FOREIGN KEY("user_id")
	REFERENCES "collect"."user"("id")
GO
ALTER TABLE "collect"."record"
	ADD CONSTRAINT "FK_record_locked_by_user"
	FOREIGN KEY("locked_by_id")
	REFERENCES "collect"."user"("id")
GO
ALTER TABLE "collect"."record"
	ADD CONSTRAINT "FK_record_created_by_user"
	FOREIGN KEY("created_by_id")
	REFERENCES "collect"."user"("id")
GO
ALTER TABLE "collect"."record"
	ADD CONSTRAINT "FK_record_modified_by_user"
	FOREIGN KEY("modified_by_id")
	REFERENCES "collect"."user"("id")
GO
