/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.openforis.idm.model {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.openforis.idm.model.CardinalityError$Reason")]
    public class CardinalityError$Reason extends Enum {

        public static const MIN_COUNT:CardinalityError$Reason = new CardinalityError$Reason("MIN_COUNT", _);
        public static const MAX_COUNT:CardinalityError$Reason = new CardinalityError$Reason("MAX_COUNT", _);
        public static const REQUIRED:CardinalityError$Reason = new CardinalityError$Reason("REQUIRED", _);

        function CardinalityError$Reason(value:String = null, restrictor:* = null) {
            super((value || MIN_COUNT.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [MIN_COUNT, MAX_COUNT, REQUIRED];
        }

        public static function valueOf(name:String):CardinalityError$Reason {
            return CardinalityError$Reason(MIN_COUNT.constantOf(name));
        }
    }
}