/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (CheckFailureImpl.as).
 */

package org.openforis.idm.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.openforis.idm.metamodel.Check;

    [Bindable]
    public class CheckFailureImplBase implements IExternalizable, CheckFailure {

        private var _check:Check;

        [Bindable(event="unused")]
        public function get check():Check {
            return _check;
        }

        public function readExternal(input:IDataInput):void {
            _check = input.readObject() as Check;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_check);
        }
    }
}