/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Code.as).
 */

package org.openforis.idm.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class CodeBase implements IExternalizable {

        private var _code:Object;
        private var _qualifier:String;

        [Bindable(event="unused")]
        public function get code():Object {
            return _code;
        }

        [Bindable(event="unused")]
        public function get qualifier():String {
            return _qualifier;
        }

        public function readExternal(input:IDataInput):void {
            _code = input.readObject() as Object;
            _qualifier = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_code);
            output.writeObject(_qualifier);
        }
    }
}