/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Coordinate.as).
 */

package org.openforis.idm.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class CoordinateBase implements IExternalizable {

        private var _srsId:String;
        private var _x:Number;
        private var _y:Number;
        private var _z:Number;

        [Bindable(event="unused")]
        public function get srsId():String {
            return _srsId;
        }

        [Bindable(event="unused")]
        public function get x():Number {
            return _x;
        }

        [Bindable(event="unused")]
        public function get y():Number {
            return _y;
        }

        [Bindable(event="unused")]
        public function get z():Number {
            return _z;
        }

        public function readExternal(input:IDataInput):void {
            _srsId = input.readObject() as String;
            _x = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _y = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _z = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_srsId);
            output.writeObject(_x);
            output.writeObject(_y);
            output.writeObject(_z);
        }
    }
}