/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Entity.as).
 */

package org.openforis.idm.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import org.granite.collections.IMap;

    [Bindable]
    public class EntityBase extends Node {

        private var _childrenByName:IMap;

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _childrenByName = input.readObject() as IMap;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_childrenByName);
        }
    }
}