/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (File.as).
 */

package org.openforis.idm.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class FileBase implements IExternalizable {

        private var _filename:String;
        private var _size:Number;

        [Bindable(event="unused")]
        public function get filename():String {
            return _filename;
        }

        [Bindable(event="unused")]
        public function get size():Number {
            return _size;
        }

        public function readExternal(input:IDataInput):void {
            _filename = input.readObject() as String;
            _size = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_filename);
            output.writeObject(_size);
        }
    }
}