/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (ModelExpression.as).
 */

package org.openforis.idm.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class ModelExpressionBase implements IExternalizable, Expression {

        private var _expression:String;

        public function readExternal(input:IDataInput):void {
            _expression = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_expression);
        }
    }
}