/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Node.as).
 */

package org.openforis.idm.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.openforis.idm.metamodel.NodeDefinition;

    [Bindable]
    public class NodeBase implements IExternalizable {

        private var _definition:NodeDefinition;
        private var _id:Number;
        private var _parent:Entity;
        private var _record:Record;

        [Bindable(event="unused")]
        public function get definition():NodeDefinition {
            return _definition;
        }

        [Bindable(event="unused")]
        public function get id():Number {
            return _id;
        }

        [Bindable(event="unused")]
        public function get parent():Entity {
            return _parent;
        }

        [Bindable(event="unused")]
        public function get record():Record {
            return _record;
        }

        public function readExternal(input:IDataInput):void {
            _definition = input.readObject() as NodeDefinition;
            _id = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _parent = input.readObject() as Entity;
            _record = input.readObject() as Record;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_definition);
            output.writeObject(_id);
            output.writeObject(_parent);
            output.writeObject(_record);
        }
    }
}