/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (NumericRange.as).
 */

package org.openforis.idm.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class NumericRangeBase implements IExternalizable {

        private var _from:Number;
        private var _to:Number;

        [Bindable(event="unused")]
        public function get from():Number {
            return _from;
        }

        [Bindable(event="unused")]
        public function get to():Number {
            return _to;
        }

        public function readExternal(input:IDataInput):void {
            _from = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _to = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_from);
            output.writeObject(_to);
        }
    }
}