/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Taxon.as).
 */

package org.openforis.idm.model {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class TaxonBase implements IExternalizable {

        private var _code:String;
        private var _languageCode:String;
        private var _languageVariant:String;
        private var _scientificName:String;
        private var _vernacularName:String;

        [Bindable(event="unused")]
        public function get code():String {
            return _code;
        }

        [Bindable(event="unused")]
        public function get languageCode():String {
            return _languageCode;
        }

        [Bindable(event="unused")]
        public function get languageVariant():String {
            return _languageVariant;
        }

        [Bindable(event="unused")]
        public function get scientificName():String {
            return _scientificName;
        }

        [Bindable(event="unused")]
        public function get vernacularName():String {
            return _vernacularName;
        }

        public function readExternal(input:IDataInput):void {
            _code = input.readObject() as String;
            _languageCode = input.readObject() as String;
            _languageVariant = input.readObject() as String;
            _scientificName = input.readObject() as String;
            _vernacularName = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_code);
            output.writeObject(_languageCode);
            output.writeObject(_languageVariant);
            output.writeObject(_scientificName);
            output.writeObject(_vernacularName);
        }
    }
}